
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-04T11:39:15-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "42a6dbd9c10fecdc5a0d71d98effe629676aafa5",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
