depends = ('ITKPyBase', 'ITKStatistics', 'ITKImageSources', 'ITKImageGrid', 'ITKCommon', )
templates = (
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS2IUL2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS3IUL3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS4IUL4', True, 'itk::Image< signed short,4 >, itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS2IUS2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS3IUS3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS4IUS4', True, 'itk::Image< signed short,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC2IUL2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC3IUL3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC4IUL4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC2IUS2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC3IUS3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC4IUS4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS2IUL2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS3IUL3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS4IUL4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF2IUL2', True, 'itk::Image< float,2 >, itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF3IUL3', True, 'itk::Image< float,3 >, itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF4IUL4', True, 'itk::Image< float,4 >, itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF2IUS2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF3IUS3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF4IUS4', True, 'itk::Image< float,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID2IUL2', True, 'itk::Image< double,2 >, itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID3IUL3', True, 'itk::Image< double,3 >, itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID4IUL4', True, 'itk::Image< double,4 >, itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID2IUS2', True, 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID3IUS3', True, 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID4IUS4', True, 'itk::Image< double,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS2IUL2', True, 'itk::VectorImage< signed short,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS2IUS2', True, 'itk::VectorImage< signed short,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC2IUL2', True, 'itk::VectorImage< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC2IUL2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC2IUS2', True, 'itk::VectorImage< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC2IUS2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS2IUL2', True, 'itk::VectorImage< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS2IUS2', True, 'itk::VectorImage< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF2IUL2', True, 'itk::VectorImage< float,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF22IUL2', True, 'itk::Image< itk::Vector< float,2 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF22IUL2', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF32IUL2', True, 'itk::Image< itk::Vector< float,3 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF32IUL2', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF42IUL2', True, 'itk::Image< itk::Vector< float,4 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF42IUL2', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF2IUS2', True, 'itk::VectorImage< float,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF22IUS2', True, 'itk::Image< itk::Vector< float,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF22IUS2', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF32IUS2', True, 'itk::Image< itk::Vector< float,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF32IUS2', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF42IUS2', True, 'itk::Image< itk::Vector< float,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF42IUS2', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID2IUL2', True, 'itk::VectorImage< double,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD22IUL2', True, 'itk::Image< itk::Vector< double,2 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD22IUL2', True, 'itk::Image< itk::CovariantVector< double,2 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD32IUL2', True, 'itk::Image< itk::Vector< double,3 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD32IUL2', True, 'itk::Image< itk::CovariantVector< double,3 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD42IUL2', True, 'itk::Image< itk::Vector< double,4 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD42IUL2', True, 'itk::Image< itk::CovariantVector< double,4 >,2 >,itk::Image< unsigned long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID2IUS2', True, 'itk::VectorImage< double,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD22IUS2', True, 'itk::Image< itk::Vector< double,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD22IUS2', True, 'itk::Image< itk::CovariantVector< double,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD32IUS2', True, 'itk::Image< itk::Vector< double,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD32IUS2', True, 'itk::Image< itk::CovariantVector< double,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD42IUS2', True, 'itk::Image< itk::Vector< double,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD42IUS2', True, 'itk::Image< itk::CovariantVector< double,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS3IUL3', True, 'itk::VectorImage< signed short,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS3IUS3', True, 'itk::VectorImage< signed short,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC3IUL3', True, 'itk::VectorImage< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC3IUL3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC3IUS3', True, 'itk::VectorImage< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC3IUS3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS3IUL3', True, 'itk::VectorImage< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS3IUS3', True, 'itk::VectorImage< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF3IUL3', True, 'itk::VectorImage< float,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF23IUL3', True, 'itk::Image< itk::Vector< float,2 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF23IUL3', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF33IUL3', True, 'itk::Image< itk::Vector< float,3 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF33IUL3', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF43IUL3', True, 'itk::Image< itk::Vector< float,4 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF43IUL3', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF3IUS3', True, 'itk::VectorImage< float,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF23IUS3', True, 'itk::Image< itk::Vector< float,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF23IUS3', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF33IUS3', True, 'itk::Image< itk::Vector< float,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF33IUS3', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF43IUS3', True, 'itk::Image< itk::Vector< float,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF43IUS3', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID3IUL3', True, 'itk::VectorImage< double,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD23IUL3', True, 'itk::Image< itk::Vector< double,2 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD23IUL3', True, 'itk::Image< itk::CovariantVector< double,2 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD33IUL3', True, 'itk::Image< itk::Vector< double,3 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD33IUL3', True, 'itk::Image< itk::CovariantVector< double,3 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD43IUL3', True, 'itk::Image< itk::Vector< double,4 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD43IUL3', True, 'itk::Image< itk::CovariantVector< double,4 >,3 >,itk::Image< unsigned long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID3IUS3', True, 'itk::VectorImage< double,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD23IUS3', True, 'itk::Image< itk::Vector< double,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD23IUS3', True, 'itk::Image< itk::CovariantVector< double,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD33IUS3', True, 'itk::Image< itk::Vector< double,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD33IUS3', True, 'itk::Image< itk::CovariantVector< double,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD43IUS3', True, 'itk::Image< itk::Vector< double,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD43IUS3', True, 'itk::Image< itk::CovariantVector< double,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS4IUL4', True, 'itk::VectorImage< signed short,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS4IUS4', True, 'itk::VectorImage< signed short,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC4IUL4', True, 'itk::VectorImage< unsigned char,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC4IUL4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC4IUS4', True, 'itk::VectorImage< unsigned char,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC4IUS4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS4IUL4', True, 'itk::VectorImage< unsigned short,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS4IUS4', True, 'itk::VectorImage< unsigned short,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF4IUL4', True, 'itk::VectorImage< float,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF24IUL4', True, 'itk::Image< itk::Vector< float,2 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF24IUL4', True, 'itk::Image< itk::CovariantVector< float,2 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF34IUL4', True, 'itk::Image< itk::Vector< float,3 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF34IUL4', True, 'itk::Image< itk::CovariantVector< float,3 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF44IUL4', True, 'itk::Image< itk::Vector< float,4 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF44IUL4', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF4IUS4', True, 'itk::VectorImage< float,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF24IUS4', True, 'itk::Image< itk::Vector< float,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF24IUS4', True, 'itk::Image< itk::CovariantVector< float,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF34IUS4', True, 'itk::Image< itk::Vector< float,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF34IUS4', True, 'itk::Image< itk::CovariantVector< float,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF44IUS4', True, 'itk::Image< itk::Vector< float,4 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF44IUS4', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID4IUL4', True, 'itk::VectorImage< double,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD24IUL4', True, 'itk::Image< itk::Vector< double,2 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD24IUL4', True, 'itk::Image< itk::CovariantVector< double,2 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD34IUL4', True, 'itk::Image< itk::Vector< double,3 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD34IUL4', True, 'itk::Image< itk::CovariantVector< double,3 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD44IUL4', True, 'itk::Image< itk::Vector< double,4 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD44IUL4', True, 'itk::Image< itk::CovariantVector< double,4 >,4 >,itk::Image< unsigned long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID4IUS4', True, 'itk::VectorImage< double,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD24IUS4', True, 'itk::Image< itk::Vector< double,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD24IUS4', True, 'itk::Image< itk::CovariantVector< double,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD34IUS4', True, 'itk::Image< itk::Vector< double,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD34IUS4', True, 'itk::Image< itk::CovariantVector< double,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD44IUS4', True, 'itk::Image< itk::Vector< double,4 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD44IUS4', True, 'itk::Image< itk::CovariantVector< double,4 >,4 >,itk::Image< unsigned short,4 >'),
)
