
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-05T17:37:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "57cc058ed2c3df1ae8c99f72fe5e6fcb8d795f39",
 "version": "v2021.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
