# coding: utf-8

"""
    Singlearity Baseball API

    Baseball optimization API using machine learning  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import singlearity
from singlearity.models.team import Team  # noqa: E501
from singlearity.rest import ApiException

class TestTeam(unittest.TestCase):
    """Team unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Team
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = singlearity.models.team.Team()  # noqa: E501
        if include_optional :
            return Team(
                abbreviation = '0', 
                division = '0', 
                league = '0', 
                id = 56, 
                name = '0', 
                team_name = '0', 
                venue = {"id":1,"name":"Angel Stadium","home_team_abbrev":"LAA","home_team_id":108}
            )
        else :
            return Team(
                abbreviation = '0',
                division = '0',
                league = '0',
                id = 56,
                name = '0',
                team_name = '0',
                venue = {"id":1,"name":"Angel Stadium","home_team_abbrev":"LAA","home_team_id":108},
        )

    def testTeam(self):
        """Test Team"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
