depends = ('ITKPyBase', 'ITKTransform', 'ITKOptimizers', 'ITKImageGrid', 'ITKDisplacementField', 'ITKCommon', )
templates = (
  ('vnl_nonlinear_minimizer', 'vnl_nonlinear_minimizer', 'vnl_nonlinear_minimizer', False),
  ('vnl_lbfgs', 'vnl_lbfgs', 'vnl_lbfgs', False),
  ('vnl_lbfgsb', 'vnl_lbfgsb', 'vnl_lbfgsb', False),
  ('LBFGSOptimizerBasev4', 'itk::LBFGSOptimizerBasev4', 'itkLBFGSOptimizerBasev4vnl_lbfgs', True, 'vnl_lbfgs'),
  ('LBFGSOptimizerBasev4', 'itk::LBFGSOptimizerBasev4', 'itkLBFGSOptimizerBasev4vnl_lbfgsb', True, 'vnl_lbfgsb'),
  ('LBFGSOptimizerBaseHelperv4', 'itk::LBFGSOptimizerBaseHelperv4', 'itkLBFGSOptimizerBaseHelperv4vnl_lbfgs', False, 'vnl_lbfgs'),
  ('LBFGSOptimizerBaseHelperv4', 'itk::LBFGSOptimizerBaseHelperv4', 'itkLBFGSOptimizerBaseHelperv4vnl_lbfgsb', False, 'vnl_lbfgsb'),
  ('LBFGSBOptimizerv4', 'itk::LBFGSBOptimizerv4', 'itkLBFGSBOptimizerv4', True),
  ('ExhaustiveOptimizerv4', 'itk::ExhaustiveOptimizerv4', 'itkExhaustiveOptimizerv4F', True, 'float'),
  ('ExhaustiveOptimizerv4', 'itk::ExhaustiveOptimizerv4', 'itkExhaustiveOptimizerv4D', True, 'double'),
  ('GradientDescentOptimizerBasev4Template', 'itk::GradientDescentOptimizerBasev4Template', 'itkGradientDescentOptimizerBasev4TemplateD', False, 'double'),
  ('GradientDescentOptimizerBasev4Template', 'itk::GradientDescentOptimizerBasev4Template', 'itkGradientDescentOptimizerBasev4TemplateF', False, 'float'),
  ('GradientDescentOptimizerv4Template', 'itk::GradientDescentOptimizerv4Template', 'itkGradientDescentOptimizerv4TemplateD', False, 'double'),
  ('GradientDescentOptimizerv4Template', 'itk::GradientDescentOptimizerv4Template', 'itkGradientDescentOptimizerv4TemplateF', False, 'float'),
  ('GradientDescentOptimizerv4', 'itk::GradientDescentOptimizerv4', 'itkGradientDescentOptimizerv4', True),
  ('ObjectToObjectMetric', 'itk::ObjectToObjectMetric', 'itkObjectToObjectMetric22', True, '2,2'),
  ('ObjectToObjectMetric', 'itk::ObjectToObjectMetric', 'itkObjectToObjectMetric33', True, '3,3'),
  ('ObjectToObjectMetric', 'itk::ObjectToObjectMetric', 'itkObjectToObjectMetric44', True, '4,4'),
  ('ObjectToObjectMetricBaseTemplateEnums', 'itk::ObjectToObjectMetricBaseTemplateEnums', 'itkObjectToObjectMetricBaseTemplateEnums', False),
  ('ObjectToObjectMetricBaseTemplate', 'itk::ObjectToObjectMetricBaseTemplate', 'itkObjectToObjectMetricBaseTemplateD', False, 'double'),
  ('ObjectToObjectMetricBaseTemplate', 'itk::ObjectToObjectMetricBaseTemplate', 'itkObjectToObjectMetricBaseTemplateF', False, 'float'),
  ('ObjectToObjectOptimizerBaseTemplateEnums', 'itk::ObjectToObjectOptimizerBaseTemplateEnums', 'itkObjectToObjectOptimizerBaseTemplateEnums', False),
  ('ObjectToObjectOptimizerBaseTemplate', 'itk::ObjectToObjectOptimizerBaseTemplate', 'itkObjectToObjectOptimizerBaseTemplateF', False, 'float'),
  ('ObjectToObjectOptimizerBaseTemplate', 'itk::ObjectToObjectOptimizerBaseTemplate', 'itkObjectToObjectOptimizerBaseTemplateD', False, 'double'),
  ('OptimizerParameterScalesEstimatorTemplate', 'itk::OptimizerParameterScalesEstimatorTemplate', 'itkOptimizerParameterScalesEstimatorTemplateD', False, 'double'),
  ('OptimizerParameterScalesEstimatorTemplate', 'itk::OptimizerParameterScalesEstimatorTemplate', 'itkOptimizerParameterScalesEstimatorTemplateF', False, 'float'),
  ('QuasiNewtonOptimizerv4Template', 'itk::QuasiNewtonOptimizerv4Template', 'itkQuasiNewtonOptimizerv4TemplateF', False, 'float'),
  ('QuasiNewtonOptimizerv4Template', 'itk::QuasiNewtonOptimizerv4Template', 'itkQuasiNewtonOptimizerv4TemplateD', False, 'double'),
  ('RegularStepGradientDescentOptimizerv4', 'itk::RegularStepGradientDescentOptimizerv4', 'itkRegularStepGradientDescentOptimizerv4D', True, 'double'),
  ('RegularStepGradientDescentOptimizerv4', 'itk::RegularStepGradientDescentOptimizerv4', 'itkRegularStepGradientDescentOptimizerv4F', True, 'float'),
  ('SingleValuedCostFunctionv4Template', 'itk::SingleValuedCostFunctionv4Template', 'itkSingleValuedCostFunctionv4TemplateD', False, 'double'),
  ('SingleValuedCostFunctionv4Template', 'itk::SingleValuedCostFunctionv4Template', 'itkSingleValuedCostFunctionv4TemplateF', False, 'float'),
  ('SingleValuedNonLinearVnlOptimizerv4', 'itk::SingleValuedNonLinearVnlOptimizerv4', 'itkSingleValuedNonLinearVnlOptimizerv4', True),
)
