# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 6, 0):
    raise RuntimeError("Python 3.6 or later required")


from . import _ITKIOSiemensPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkSiemensVisionImageIOPython
else:
    import _itkSiemensVisionImageIOPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkSiemensVisionImageIOPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkSiemensVisionImageIOPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import collections.abc
import itk.itkIPLCommonImageIOPython
import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.ITKIOImageBaseBasePython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython

def itkSiemensVisionImageIO_New():
    return itkSiemensVisionImageIO.New()

class itkSiemensVisionImageIO(itk.itkIPLCommonImageIOPython.itkIPLCommonImageIO):
    r"""


    Class that defines how to read SiemensVision file format.

    Hans J. Johnson 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkSiemensVisionImageIOPython.itkSiemensVisionImageIO___New_orig__)
    Clone = _swig_new_instance_method(_itkSiemensVisionImageIOPython.itkSiemensVisionImageIO_Clone)
    __swig_destroy__ = _itkSiemensVisionImageIOPython.delete_itkSiemensVisionImageIO
    cast = _swig_new_static_method(_itkSiemensVisionImageIOPython.itkSiemensVisionImageIO_cast)

    def New(*args, **kargs):
        """New() -> itkSiemensVisionImageIO

        Create a new object of the class itkSiemensVisionImageIO and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSiemensVisionImageIO.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkSiemensVisionImageIO.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkSiemensVisionImageIO.__New_orig__()
        from itk.support import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkSiemensVisionImageIO in _itkSiemensVisionImageIOPython:
_itkSiemensVisionImageIOPython.itkSiemensVisionImageIO_swigregister(itkSiemensVisionImageIO)
itkSiemensVisionImageIO___New_orig__ = _itkSiemensVisionImageIOPython.itkSiemensVisionImageIO___New_orig__
itkSiemensVisionImageIO_cast = _itkSiemensVisionImageIOPython.itkSiemensVisionImageIO_cast


def itkSiemensVisionImageIOFactory_New():
    return itkSiemensVisionImageIOFactory.New()

class itkSiemensVisionImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    r"""


    Create instances of SiemensVisionImageIO objects using an object
    factory. 
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory___New_orig__)
    RegisterOneFactory = _swig_new_static_method(_itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory_RegisterOneFactory)
    __swig_destroy__ = _itkSiemensVisionImageIOPython.delete_itkSiemensVisionImageIOFactory
    cast = _swig_new_static_method(_itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory_cast)

    def New(*args, **kargs):
        """New() -> itkSiemensVisionImageIOFactory

        Create a new object of the class itkSiemensVisionImageIOFactory and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkSiemensVisionImageIOFactory.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkSiemensVisionImageIOFactory.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkSiemensVisionImageIOFactory.__New_orig__()
        from itk.support import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkSiemensVisionImageIOFactory in _itkSiemensVisionImageIOPython:
_itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory_swigregister(itkSiemensVisionImageIOFactory)
itkSiemensVisionImageIOFactory___New_orig__ = _itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory___New_orig__
itkSiemensVisionImageIOFactory_RegisterOneFactory = _itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory_RegisterOneFactory
itkSiemensVisionImageIOFactory_cast = _itkSiemensVisionImageIOPython.itkSiemensVisionImageIOFactory_cast



