
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-04T22:45:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "35fded0687b4d96155c1dc7834ddea9a2d249f33",
 "version": "2021.02.27a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
