
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-04T18:37:09+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dc2f9a3aef31d4822172752899a50c663f14ef0",
 "version": "0.3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
