MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 3
VERSION = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)


__all__ = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'VERSION']
