# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.mayaviWidgetGeo = MayaviQWidget_geo(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.mayaviWidgetGeo.sizePolicy().hasHeightForWidth())
        self.mayaviWidgetGeo.setSizePolicy(sizePolicy)
        self.mayaviWidgetGeo.setMinimumSize(QtCore.QSize(400, 400))
        self.mayaviWidgetGeo.setObjectName("mayaviWidgetGeo")
        self.gridLayout.addWidget(self.mayaviWidgetGeo, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_41 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_26.addWidget(self.label_41)
        self.comboBoxDyads = QtWidgets.QComboBox(self.tab)
        self.comboBoxDyads.setObjectName("comboBoxDyads")
        self.horizontalLayout_26.addWidget(self.comboBoxDyads)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEditN1 = QtWidgets.QLineEdit(self.tab)
        self.lineEditN1.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditN1.setObjectName("lineEditN1")
        self.horizontalLayout_4.addWidget(self.lineEditN1)
        self.lineEditN2 = QtWidgets.QLineEdit(self.tab)
        self.lineEditN2.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditN2.setObjectName("lineEditN2")
        self.horizontalLayout_4.addWidget(self.lineEditN2)
        self.lineEditN3 = QtWidgets.QLineEdit(self.tab)
        self.lineEditN3.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditN3.setObjectName("lineEditN3")
        self.horizontalLayout_4.addWidget(self.lineEditN3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(150, 0))
        self.label_8.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEditSpacing = QtWidgets.QLineEdit(self.tab)
        self.lineEditSpacing.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditSpacing.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditSpacing.setObjectName("lineEditSpacing")
        self.horizontalLayout_5.addWidget(self.lineEditSpacing)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(9999999, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEditStep = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStep.sizePolicy().hasHeightForWidth())
        self.lineEditStep.setSizePolicy(sizePolicy)
        self.lineEditStep.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditStep.setObjectName("lineEditStep")
        self.gridLayout_2.addWidget(self.lineEditStep, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.comboBoxMaterial = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMaterial.sizePolicy().hasHeightForWidth())
        self.comboBoxMaterial.setSizePolicy(sizePolicy)
        self.comboBoxMaterial.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.comboBoxMaterial.setObjectName("comboBoxMaterial")
        self.gridLayout_2.addWidget(self.comboBoxMaterial, 5, 1, 1, 1)
        self.comboBoxMesh = QtWidgets.QComboBox(self.tab)
        self.comboBoxMesh.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.comboBoxMesh.setObjectName("comboBoxMesh")
        self.gridLayout_2.addWidget(self.comboBoxMesh, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tableWidgetMaterialParams = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetMaterialParams.setMinimumSize(QtCore.QSize(0, 80))
        self.tableWidgetMaterialParams.setMaximumSize(QtCore.QSize(9999999, 120))
        self.tableWidgetMaterialParams.setObjectName("tableWidgetMaterialParams")
        self.tableWidgetMaterialParams.setColumnCount(0)
        self.tableWidgetMaterialParams.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidgetMaterialParams)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.comboBoxGeo = QtWidgets.QComboBox(self.tab)
        self.comboBoxGeo.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.comboBoxGeo.setObjectName("comboBoxGeo")
        self.horizontalLayout_2.addWidget(self.comboBoxGeo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidgetGeoParams = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetGeoParams.setMinimumSize(QtCore.QSize(110, 0))
        self.tableWidgetGeoParams.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.tableWidgetGeoParams.setObjectName("tableWidgetGeoParams")
        self.tableWidgetGeoParams.setColumnCount(0)
        self.tableWidgetGeoParams.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidgetGeoParams)
        self.pushButtonAddGeo = QtWidgets.QPushButton(self.tab)
        self.pushButtonAddGeo.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddGeo.setFont(font)
        self.pushButtonAddGeo.setObjectName("pushButtonAddGeo")
        self.verticalLayout_2.addWidget(self.pushButtonAddGeo)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_25.addWidget(self.label_9)
        self.checkBoxGeoMaterialLabels = QtWidgets.QCheckBox(self.tab)
        self.checkBoxGeoMaterialLabels.setChecked(True)
        self.checkBoxGeoMaterialLabels.setObjectName("checkBoxGeoMaterialLabels")
        self.horizontalLayout_25.addWidget(self.checkBoxGeoMaterialLabels)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.listWidgetStructures = QtWidgets.QListWidget(self.tab)
        self.listWidgetStructures.setMinimumSize(QtCore.QSize(0, 100))
        self.listWidgetStructures.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.listWidgetStructures.setObjectName("listWidgetStructures")
        self.verticalLayout_2.addWidget(self.listWidgetStructures)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonDelGeo = QtWidgets.QPushButton(self.tab)
        self.pushButtonDelGeo.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonDelGeo.setObjectName("pushButtonDelGeo")
        self.horizontalLayout_6.addWidget(self.pushButtonDelGeo)
        self.pushButtonClearGeo = QtWidgets.QPushButton(self.tab)
        self.pushButtonClearGeo.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonClearGeo.setObjectName("pushButtonClearGeo")
        self.horizontalLayout_6.addWidget(self.pushButtonClearGeo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButtonOffsetXpOne = QtWidgets.QPushButton(self.tab)
        self.pushButtonOffsetXpOne.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonOffsetXpOne.setObjectName("pushButtonOffsetXpOne")
        self.horizontalLayout_13.addWidget(self.pushButtonOffsetXpOne)
        self.pushButtonOffsetXmOne = QtWidgets.QPushButton(self.tab)
        self.pushButtonOffsetXmOne.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonOffsetXmOne.setObjectName("pushButtonOffsetXmOne")
        self.horizontalLayout_13.addWidget(self.pushButtonOffsetXmOne)
        self.pushButtonOffsetYpOne = QtWidgets.QPushButton(self.tab)
        self.pushButtonOffsetYpOne.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonOffsetYpOne.setObjectName("pushButtonOffsetYpOne")
        self.horizontalLayout_13.addWidget(self.pushButtonOffsetYpOne)
        self.pushButtonOffsetYmOne = QtWidgets.QPushButton(self.tab)
        self.pushButtonOffsetYmOne.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonOffsetYmOne.setObjectName("pushButtonOffsetYmOne")
        self.horizontalLayout_13.addWidget(self.pushButtonOffsetYmOne)
        self.pushButtonOffsetZpOne = QtWidgets.QPushButton(self.tab)
        self.pushButtonOffsetZpOne.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonOffsetZpOne.setObjectName("pushButtonOffsetZpOne")
        self.horizontalLayout_13.addWidget(self.pushButtonOffsetZpOne)
        self.pushButtonOffsetZmOne = QtWidgets.QPushButton(self.tab)
        self.pushButtonOffsetZmOne.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonOffsetZmOne.setObjectName("pushButtonOffsetZmOne")
        self.horizontalLayout_13.addWidget(self.pushButtonOffsetZmOne)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.line_14 = QtWidgets.QFrame(self.tab)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_2.addWidget(self.line_14)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditOffsetZ = QtWidgets.QLineEdit(self.tab)
        self.lineEditOffsetZ.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditOffsetZ.setObjectName("lineEditOffsetZ")
        self.gridLayout_3.addWidget(self.lineEditOffsetZ, 0, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 2, 1, 1)
        self.lineEditOffsetX = QtWidgets.QLineEdit(self.tab)
        self.lineEditOffsetX.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditOffsetX.setObjectName("lineEditOffsetX")
        self.gridLayout_3.addWidget(self.lineEditOffsetX, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEditOffsetY = QtWidgets.QLineEdit(self.tab)
        self.lineEditOffsetY.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditOffsetY.setObjectName("lineEditOffsetY")
        self.gridLayout_3.addWidget(self.lineEditOffsetY, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButtonApplyOffsetGeo = QtWidgets.QPushButton(self.tab)
        self.pushButtonApplyOffsetGeo.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonApplyOffsetGeo.setObjectName("pushButtonApplyOffsetGeo")
        self.horizontalLayout_19.addWidget(self.pushButtonApplyOffsetGeo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.pushButtonApplyRotationGeo = QtWidgets.QPushButton(self.tab)
        self.pushButtonApplyRotationGeo.setObjectName("pushButtonApplyRotationGeo")
        self.verticalLayout_2.addWidget(self.pushButtonApplyRotationGeo)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 9)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.lineEditWl0 = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWl0.sizePolicy().hasHeightForWidth())
        self.lineEditWl0.setSizePolicy(sizePolicy)
        self.lineEditWl0.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditWl0.setObjectName("lineEditWl0")
        self.horizontalLayout_10.addWidget(self.lineEditWl0)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.lineEditWl1 = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWl1.sizePolicy().hasHeightForWidth())
        self.lineEditWl1.setSizePolicy(sizePolicy)
        self.lineEditWl1.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditWl1.setObjectName("lineEditWl1")
        self.horizontalLayout_10.addWidget(self.lineEditWl1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.lineEditNwl = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEditNwl.sizePolicy().hasHeightForWidth())
        self.lineEditNwl.setSizePolicy(sizePolicy)
        self.lineEditNwl.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.lineEditNwl.setObjectName("lineEditNwl")
        self.horizontalLayout_10.addWidget(self.lineEditNwl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_4.addWidget(self.line_8)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.comboBoxFieldGen = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxFieldGen.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.comboBoxFieldGen.setObjectName("comboBoxFieldGen")
        self.horizontalLayout_11.addWidget(self.comboBoxFieldGen)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.tableWidgetFieldParams = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetFieldParams.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.tableWidgetFieldParams.setObjectName("tableWidgetFieldParams")
        self.tableWidgetFieldParams.setColumnCount(0)
        self.tableWidgetFieldParams.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidgetFieldParams)
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_4.addWidget(self.line_9)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_15.addWidget(self.label_37)
        self.comboBoxInversionMethod = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxInversionMethod.sizePolicy().hasHeightForWidth())
        self.comboBoxInversionMethod.setSizePolicy(sizePolicy)
        self.comboBoxInversionMethod.setObjectName("comboBoxInversionMethod")
        self.comboBoxInversionMethod.addItem("")
        self.comboBoxInversionMethod.addItem("")
        self.comboBoxInversionMethod.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBoxInversionMethod)
        self.checkBoxCalcH = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxCalcH.setChecked(True)
        self.checkBoxCalcH.setObjectName("checkBoxCalcH")
        self.horizontalLayout_15.addWidget(self.checkBoxCalcH)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButtonStartSim = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartSim.sizePolicy().hasHeightForWidth())
        self.pushButtonStartSim.setSizePolicy(sizePolicy)
        self.pushButtonStartSim.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStartSim.setFont(font)
        self.pushButtonStartSim.setObjectName("pushButtonStartSim")
        self.horizontalLayout_12.addWidget(self.pushButtonStartSim)
        self.pushButtonCancelSim = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonCancelSim.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCancelSim.sizePolicy().hasHeightForWidth())
        self.pushButtonCancelSim.setSizePolicy(sizePolicy)
        self.pushButtonCancelSim.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonCancelSim.setObjectName("pushButtonCancelSim")
        self.horizontalLayout_12.addWidget(self.pushButtonCancelSim)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.line_11 = QtWidgets.QFrame(self.tab_2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_4.addWidget(self.line_11)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.textEditSimStatus = QtWidgets.QTextEdit(self.tab_2)
        self.textEditSimStatus.setMinimumSize(QtCore.QSize(0, 200))
        self.textEditSimStatus.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textEditSimStatus.setFont(font)
        self.textEditSimStatus.setObjectName("textEditSimStatus")
        self.verticalLayout_4.addWidget(self.textEditSimStatus)
        self.progressBarSim = QtWidgets.QProgressBar(self.tab_2)
        self.progressBarSim.setProperty("value", 0)
        self.progressBarSim.setObjectName("progressBarSim")
        self.verticalLayout_4.addWidget(self.progressBarSim)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.listWidgetAvailableWavelengths = QtWidgets.QListWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.listWidgetAvailableWavelengths.sizePolicy().hasHeightForWidth())
        self.listWidgetAvailableWavelengths.setSizePolicy(sizePolicy)
        self.listWidgetAvailableWavelengths.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.listWidgetAvailableWavelengths.setObjectName("listWidgetAvailableWavelengths")
        self.verticalLayout_7.addWidget(self.listWidgetAvailableWavelengths)
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_7.addWidget(self.line_10)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.listWidgetAvailableFieldConfigs = QtWidgets.QListWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.listWidgetAvailableFieldConfigs.sizePolicy().hasHeightForWidth())
        self.listWidgetAvailableFieldConfigs.setSizePolicy(sizePolicy)
        self.listWidgetAvailableFieldConfigs.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.listWidgetAvailableFieldConfigs.setObjectName("listWidgetAvailableFieldConfigs")
        self.verticalLayout_7.addWidget(self.listWidgetAvailableFieldConfigs)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.plainTextEditSelectedConfig = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEditSelectedConfig.setMaximumSize(QtCore.QSize(9999999, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.plainTextEditSelectedConfig.setFont(font)
        self.plainTextEditSelectedConfig.setObjectName("plainTextEditSelectedConfig")
        self.verticalLayout_7.addWidget(self.plainTextEditSelectedConfig)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_7.addWidget(self.line_12)
        self.pushButtonQuicksaveSim = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonQuicksaveSim.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonQuicksaveSim.setObjectName("pushButtonQuicksaveSim")
        self.verticalLayout_7.addWidget(self.pushButtonQuicksaveSim)
        self.pushButtonQuickloadSim = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonQuickloadSim.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.pushButtonQuickloadSim.setObjectName("pushButtonQuickloadSim")
        self.verticalLayout_7.addWidget(self.pushButtonQuickloadSim)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_internalfields = QtWidgets.QWidget()
        self.tab_internalfields.setObjectName("tab_internalfields")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tab_internalfields)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBoxUpdateLatest = QtWidgets.QCheckBox(self.tab_internalfields)
        self.checkBoxUpdateLatest.setChecked(False)
        self.checkBoxUpdateLatest.setTristate(False)
        self.checkBoxUpdateLatest.setObjectName("checkBoxUpdateLatest")
        self.verticalLayout_13.addWidget(self.checkBoxUpdateLatest)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.tab_internalfields)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.lineEditAnimateIntFieldScale = QtWidgets.QLineEdit(self.tab_internalfields)
        self.lineEditAnimateIntFieldScale.setObjectName("lineEditAnimateIntFieldScale")
        self.horizontalLayout_17.addWidget(self.lineEditAnimateIntFieldScale)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.pushButtonToggleAnimateIntField = QtWidgets.QPushButton(self.tab_internalfields)
        self.pushButtonToggleAnimateIntField.setObjectName("pushButtonToggleAnimateIntField")
        self.verticalLayout_13.addWidget(self.pushButtonToggleAnimateIntField)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.tab_internalfields)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.lineEditAnimateIntFieldfps = QtWidgets.QLineEdit(self.tab_internalfields)
        self.lineEditAnimateIntFieldfps.setObjectName("lineEditAnimateIntFieldfps")
        self.horizontalLayout_14.addWidget(self.lineEditAnimateIntFieldfps)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.label_25 = QtWidgets.QLabel(self.tab_internalfields)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_13.addWidget(self.label_25)
        self.horizontalSliderPlotMomentOpticalCycleIntField = QtWidgets.QSlider(self.tab_internalfields)
        self.horizontalSliderPlotMomentOpticalCycleIntField.setMaximum(99)
        self.horizontalSliderPlotMomentOpticalCycleIntField.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPlotMomentOpticalCycleIntField.setObjectName("horizontalSliderPlotMomentOpticalCycleIntField")
        self.verticalLayout_13.addWidget(self.horizontalSliderPlotMomentOpticalCycleIntField)
        self.line_16 = QtWidgets.QFrame(self.tab_internalfields)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_13.addWidget(self.line_16)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.radioButtonE = QtWidgets.QRadioButton(self.tab_internalfields)
        self.radioButtonE.setChecked(True)
        self.radioButtonE.setObjectName("radioButtonE")
        self.horizontalLayout_27.addWidget(self.radioButtonE)
        self.radioButtonH = QtWidgets.QRadioButton(self.tab_internalfields)
        self.radioButtonH.setObjectName("radioButtonH")
        self.horizontalLayout_27.addWidget(self.radioButtonH)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.horizontalLayout_20.addLayout(self.verticalLayout_13)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mayaviWidgetNF = MayaviQWidget_NF(self.tab_internalfields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.mayaviWidgetNF.sizePolicy().hasHeightForWidth())
        self.mayaviWidgetNF.setSizePolicy(sizePolicy)
        self.mayaviWidgetNF.setMinimumSize(QtCore.QSize(500, 0))
        self.mayaviWidgetNF.setObjectName("mayaviWidgetNF")
        self.verticalLayout_6.addWidget(self.mayaviWidgetNF)
        self.line_13 = QtWidgets.QFrame(self.tab_internalfields)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_6.addWidget(self.line_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widgetMPL_2dNF_XY = MplWidget(self.tab_internalfields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetMPL_2dNF_XY.sizePolicy().hasHeightForWidth())
        self.widgetMPL_2dNF_XY.setSizePolicy(sizePolicy)
        self.widgetMPL_2dNF_XY.setMinimumSize(QtCore.QSize(100, 100))
        self.widgetMPL_2dNF_XY.setObjectName("widgetMPL_2dNF_XY")
        self.horizontalLayout_9.addWidget(self.widgetMPL_2dNF_XY)
        self.widgetMPL_2dNF_XZ = MplWidget(self.tab_internalfields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetMPL_2dNF_XZ.sizePolicy().hasHeightForWidth())
        self.widgetMPL_2dNF_XZ.setSizePolicy(sizePolicy)
        self.widgetMPL_2dNF_XZ.setMinimumSize(QtCore.QSize(100, 100))
        self.widgetMPL_2dNF_XZ.setObjectName("widgetMPL_2dNF_XZ")
        self.horizontalLayout_9.addWidget(self.widgetMPL_2dNF_XZ)
        self.widgetMPL_2dNF_YZ = MplWidget(self.tab_internalfields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetMPL_2dNF_YZ.sizePolicy().hasHeightForWidth())
        self.widgetMPL_2dNF_YZ.setSizePolicy(sizePolicy)
        self.widgetMPL_2dNF_YZ.setMinimumSize(QtCore.QSize(100, 100))
        self.widgetMPL_2dNF_YZ.setObjectName("widgetMPL_2dNF_YZ")
        self.horizontalLayout_9.addWidget(self.widgetMPL_2dNF_YZ)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 2)
        self.horizontalLayout_9.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.setStretch(0, 3)
        self.verticalLayout_6.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_6)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 9)
        self.tabWidget_2.addTab(self.tab_internalfields, "")
        self.tab_spectra = QtWidgets.QWidget()
        self.tab_spectra.setObjectName("tab_spectra")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.tab_spectra)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.tab_spectra)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.line_18 = QtWidgets.QFrame(self.tab_spectra)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_11.addWidget(self.line_18)
        self.label_28 = QtWidgets.QLabel(self.tab_spectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_28.setObjectName("label_28")
        self.verticalLayout_11.addWidget(self.label_28)
        self.listWidgetAvailableSpectraFuncs = QtWidgets.QListWidget(self.tab_spectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidgetAvailableSpectraFuncs.sizePolicy().hasHeightForWidth())
        self.listWidgetAvailableSpectraFuncs.setSizePolicy(sizePolicy)
        self.listWidgetAvailableSpectraFuncs.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.listWidgetAvailableSpectraFuncs.setObjectName("listWidgetAvailableSpectraFuncs")
        self.verticalLayout_11.addWidget(self.listWidgetAvailableSpectraFuncs)
        self.pushButtonCalcSpectrum1 = QtWidgets.QPushButton(self.tab_spectra)
        self.pushButtonCalcSpectrum1.setObjectName("pushButtonCalcSpectrum1")
        self.verticalLayout_11.addWidget(self.pushButtonCalcSpectrum1)
        self.line_20 = QtWidgets.QFrame(self.tab_spectra)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_11.addWidget(self.line_20)
        self.label_35 = QtWidgets.QLabel(self.tab_spectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_35.setObjectName("label_35")
        self.verticalLayout_11.addWidget(self.label_35)
        self.tableWidgetSpectraFuncConfig = QtWidgets.QTableWidget(self.tab_spectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidgetSpectraFuncConfig.sizePolicy().hasHeightForWidth())
        self.tableWidgetSpectraFuncConfig.setSizePolicy(sizePolicy)
        self.tableWidgetSpectraFuncConfig.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.tableWidgetSpectraFuncConfig.setObjectName("tableWidgetSpectraFuncConfig")
        self.tableWidgetSpectraFuncConfig.setColumnCount(0)
        self.tableWidgetSpectraFuncConfig.setRowCount(0)
        self.verticalLayout_11.addWidget(self.tableWidgetSpectraFuncConfig)
        self.checkBoxSepPlotsSpectra = QtWidgets.QCheckBox(self.tab_spectra)
        self.checkBoxSepPlotsSpectra.setChecked(True)
        self.checkBoxSepPlotsSpectra.setObjectName("checkBoxSepPlotsSpectra")
        self.verticalLayout_11.addWidget(self.checkBoxSepPlotsSpectra)
        self.checkBoxClearPlotsSpectra = QtWidgets.QCheckBox(self.tab_spectra)
        self.checkBoxClearPlotsSpectra.setObjectName("checkBoxClearPlotsSpectra")
        self.verticalLayout_11.addWidget(self.checkBoxClearPlotsSpectra)
        self.pushButtonCalcSpectrum2 = QtWidgets.QPushButton(self.tab_spectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalcSpectrum2.sizePolicy().hasHeightForWidth())
        self.pushButtonCalcSpectrum2.setSizePolicy(sizePolicy)
        self.pushButtonCalcSpectrum2.setObjectName("pushButtonCalcSpectrum2")
        self.verticalLayout_11.addWidget(self.pushButtonCalcSpectrum2)
        self.pushButtonSaveSpec = QtWidgets.QPushButton(self.tab_spectra)
        self.pushButtonSaveSpec.setObjectName("pushButtonSaveSpec")
        self.verticalLayout_11.addWidget(self.pushButtonSaveSpec)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widgetMPLspectrum = MplWidget(self.tab_spectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widgetMPLspectrum.sizePolicy().hasHeightForWidth())
        self.widgetMPLspectrum.setSizePolicy(sizePolicy)
        self.widgetMPLspectrum.setMinimumSize(QtCore.QSize(100, 100))
        self.widgetMPLspectrum.setObjectName("widgetMPLspectrum")
        self.verticalLayout_12.addWidget(self.widgetMPLspectrum)
        self.horizontalLayout_21.addLayout(self.verticalLayout_12)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 6)
        self.tabWidget_2.addTab(self.tab_spectra, "")
        self.tab_mapping = QtWidgets.QWidget()
        self.tab_mapping.setObjectName("tab_mapping")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.tab_mapping)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_30 = QtWidgets.QLabel(self.tab_mapping)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_9.addWidget(self.label_30)
        self.line_17 = QtWidgets.QFrame(self.tab_mapping)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_9.addWidget(self.line_17)
        self.label_26 = QtWidgets.QLabel(self.tab_mapping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.listWidgetAvailableMappingFuncs = QtWidgets.QListWidget(self.tab_mapping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidgetAvailableMappingFuncs.sizePolicy().hasHeightForWidth())
        self.listWidgetAvailableMappingFuncs.setSizePolicy(sizePolicy)
        self.listWidgetAvailableMappingFuncs.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.listWidgetAvailableMappingFuncs.setObjectName("listWidgetAvailableMappingFuncs")
        self.verticalLayout_9.addWidget(self.listWidgetAvailableMappingFuncs)
        self.pushButtonCalcMapping1 = QtWidgets.QPushButton(self.tab_mapping)
        self.pushButtonCalcMapping1.setObjectName("pushButtonCalcMapping1")
        self.verticalLayout_9.addWidget(self.pushButtonCalcMapping1)
        self.line_15 = QtWidgets.QFrame(self.tab_mapping)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_9.addWidget(self.line_15)
        self.label_27 = QtWidgets.QLabel(self.tab_mapping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_27.setObjectName("label_27")
        self.verticalLayout_9.addWidget(self.label_27)
        self.tableWidgetMappingFuncConfig = QtWidgets.QTableWidget(self.tab_mapping)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidgetMappingFuncConfig.sizePolicy().hasHeightForWidth())
        self.tableWidgetMappingFuncConfig.setSizePolicy(sizePolicy)
        self.tableWidgetMappingFuncConfig.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.tableWidgetMappingFuncConfig.setObjectName("tableWidgetMappingFuncConfig")
        self.tableWidgetMappingFuncConfig.setColumnCount(0)
        self.tableWidgetMappingFuncConfig.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tableWidgetMappingFuncConfig)
        self.checkBoxMappingGeoContour = QtWidgets.QCheckBox(self.tab_mapping)
        self.checkBoxMappingGeoContour.setChecked(True)
        self.checkBoxMappingGeoContour.setObjectName("checkBoxMappingGeoContour")
        self.verticalLayout_9.addWidget(self.checkBoxMappingGeoContour)
        self.checkBoxSepPlotsMapping = QtWidgets.QCheckBox(self.tab_mapping)
        self.checkBoxSepPlotsMapping.setChecked(True)
        self.checkBoxSepPlotsMapping.setObjectName("checkBoxSepPlotsMapping")
        self.verticalLayout_9.addWidget(self.checkBoxSepPlotsMapping)
        self.checkBoxClearPlotsMapping = QtWidgets.QCheckBox(self.tab_mapping)
        self.checkBoxClearPlotsMapping.setObjectName("checkBoxClearPlotsMapping")
        self.verticalLayout_9.addWidget(self.checkBoxClearPlotsMapping)
        self.pushButtonCalcMapping2 = QtWidgets.QPushButton(self.tab_mapping)
        self.pushButtonCalcMapping2.setObjectName("pushButtonCalcMapping2")
        self.verticalLayout_9.addWidget(self.pushButtonCalcMapping2)
        self.pushButtonSaveMapping = QtWidgets.QPushButton(self.tab_mapping)
        self.pushButtonSaveMapping.setObjectName("pushButtonSaveMapping")
        self.verticalLayout_9.addWidget(self.pushButtonSaveMapping)
        self.horizontalLayout_22.addLayout(self.verticalLayout_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetMPLmapping = MplWidget(self.tab_mapping)
        self.widgetMPLmapping.setObjectName("widgetMPLmapping")
        self.verticalLayout_3.addWidget(self.widgetMPLmapping)
        self.horizontalLayout_22.addLayout(self.verticalLayout_3)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 6)
        self.tabWidget_2.addTab(self.tab_mapping, "")
        self.tab_rasterscan = QtWidgets.QWidget()
        self.tab_rasterscan.setObjectName("tab_rasterscan")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.tab_rasterscan)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_38 = QtWidgets.QLabel(self.tab_rasterscan)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_14.addWidget(self.label_38)
        self.line_21 = QtWidgets.QFrame(self.tab_rasterscan)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_14.addWidget(self.line_21)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_32 = QtWidgets.QLabel(self.tab_rasterscan)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        self.lineEditResterscanXkey = QtWidgets.QLineEdit(self.tab_rasterscan)
        self.lineEditResterscanXkey.setObjectName("lineEditResterscanXkey")
        self.horizontalLayout_18.addWidget(self.lineEditResterscanXkey)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_33 = QtWidgets.QLabel(self.tab_rasterscan)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_24.addWidget(self.label_33)
        self.lineEditResterscanYkey = QtWidgets.QLineEdit(self.tab_rasterscan)
        self.lineEditResterscanYkey.setObjectName("lineEditResterscanYkey")
        self.horizontalLayout_24.addWidget(self.lineEditResterscanYkey)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.label_31 = QtWidgets.QLabel(self.tab_rasterscan)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_14.addWidget(self.label_31)
        self.listWidgetRasterscanFieldconfig = QtWidgets.QListWidget(self.tab_rasterscan)
        self.listWidgetRasterscanFieldconfig.setObjectName("listWidgetRasterscanFieldconfig")
        self.verticalLayout_14.addWidget(self.listWidgetRasterscanFieldconfig)
        self.label_39 = QtWidgets.QLabel(self.tab_rasterscan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_39.setObjectName("label_39")
        self.verticalLayout_14.addWidget(self.label_39)
        self.listWidgetAvailableRasterscanFuncs = QtWidgets.QListWidget(self.tab_rasterscan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidgetAvailableRasterscanFuncs.sizePolicy().hasHeightForWidth())
        self.listWidgetAvailableRasterscanFuncs.setSizePolicy(sizePolicy)
        self.listWidgetAvailableRasterscanFuncs.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.listWidgetAvailableRasterscanFuncs.setObjectName("listWidgetAvailableRasterscanFuncs")
        self.verticalLayout_14.addWidget(self.listWidgetAvailableRasterscanFuncs)
        self.pushButtonCalcRasterscan1 = QtWidgets.QPushButton(self.tab_rasterscan)
        self.pushButtonCalcRasterscan1.setObjectName("pushButtonCalcRasterscan1")
        self.verticalLayout_14.addWidget(self.pushButtonCalcRasterscan1)
        self.line_22 = QtWidgets.QFrame(self.tab_rasterscan)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_14.addWidget(self.line_22)
        self.label_40 = QtWidgets.QLabel(self.tab_rasterscan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.label_40.setObjectName("label_40")
        self.verticalLayout_14.addWidget(self.label_40)
        self.tableWidgetRasterscanFuncConfig = QtWidgets.QTableWidget(self.tab_rasterscan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidgetRasterscanFuncConfig.sizePolicy().hasHeightForWidth())
        self.tableWidgetRasterscanFuncConfig.setSizePolicy(sizePolicy)
        self.tableWidgetRasterscanFuncConfig.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.tableWidgetRasterscanFuncConfig.setObjectName("tableWidgetRasterscanFuncConfig")
        self.tableWidgetRasterscanFuncConfig.setColumnCount(0)
        self.tableWidgetRasterscanFuncConfig.setRowCount(0)
        self.verticalLayout_14.addWidget(self.tableWidgetRasterscanFuncConfig)
        self.checkBoxRasterscanGeoContour = QtWidgets.QCheckBox(self.tab_rasterscan)
        self.checkBoxRasterscanGeoContour.setChecked(True)
        self.checkBoxRasterscanGeoContour.setObjectName("checkBoxRasterscanGeoContour")
        self.verticalLayout_14.addWidget(self.checkBoxRasterscanGeoContour)
        self.checkBoxSepPlotsRasterscan = QtWidgets.QCheckBox(self.tab_rasterscan)
        self.checkBoxSepPlotsRasterscan.setChecked(True)
        self.checkBoxSepPlotsRasterscan.setObjectName("checkBoxSepPlotsRasterscan")
        self.verticalLayout_14.addWidget(self.checkBoxSepPlotsRasterscan)
        self.checkBoxClearPlotsRasterscan = QtWidgets.QCheckBox(self.tab_rasterscan)
        self.checkBoxClearPlotsRasterscan.setObjectName("checkBoxClearPlotsRasterscan")
        self.verticalLayout_14.addWidget(self.checkBoxClearPlotsRasterscan)
        self.pushButtonCalcRasterscan2 = QtWidgets.QPushButton(self.tab_rasterscan)
        self.pushButtonCalcRasterscan2.setObjectName("pushButtonCalcRasterscan2")
        self.verticalLayout_14.addWidget(self.pushButtonCalcRasterscan2)
        self.pushButtonSaveRasterscan = QtWidgets.QPushButton(self.tab_rasterscan)
        self.pushButtonSaveRasterscan.setObjectName("pushButtonSaveRasterscan")
        self.verticalLayout_14.addWidget(self.pushButtonSaveRasterscan)
        self.progressBarRasterscan = QtWidgets.QProgressBar(self.tab_rasterscan)
        self.progressBarRasterscan.setProperty("value", 0)
        self.progressBarRasterscan.setObjectName("progressBarRasterscan")
        self.verticalLayout_14.addWidget(self.progressBarRasterscan)
        self.horizontalLayout_23.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widgetMPLrasterscan = MplWidget(self.tab_rasterscan)
        self.widgetMPLrasterscan.setObjectName("widgetMPLrasterscan")
        self.verticalLayout_15.addWidget(self.widgetMPLrasterscan)
        self.horizontalLayout_23.addLayout(self.verticalLayout_15)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 6)
        self.tabWidget_2.addTab(self.tab_rasterscan, "")
        self.horizontalLayout_8.addWidget(self.tabWidget_2)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 10)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_16.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 29))
        self.menubar.setObjectName("menubar")
        self.menusimulation = QtWidgets.QMenu(self.menubar)
        self.menusimulation.setObjectName("menusimulation")
        self.menusave_results = QtWidgets.QMenu(self.menubar)
        self.menusave_results.setObjectName("menusave_results")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionload_struct = QtWidgets.QAction(MainWindow)
        self.actionload_struct.setObjectName("actionload_struct")
        self.actionload_sim = QtWidgets.QAction(MainWindow)
        self.actionload_sim.setObjectName("actionload_sim")
        self.actionsave_sim = QtWidgets.QAction(MainWindow)
        self.actionsave_sim.setObjectName("actionsave_sim")
        self.actionsave_struct = QtWidgets.QAction(MainWindow)
        self.actionsave_struct.setObjectName("actionsave_struct")
        self.actionsave_structure = QtWidgets.QAction(MainWindow)
        self.actionsave_structure.setObjectName("actionsave_structure")
        self.actionload_structure = QtWidgets.QAction(MainWindow)
        self.actionload_structure.setObjectName("actionload_structure")
        self.actionsave_structure_as_txt = QtWidgets.QAction(MainWindow)
        self.actionsave_structure_as_txt.setObjectName("actionsave_structure_as_txt")
        self.actionsave_last_calculated_spectra = QtWidgets.QAction(MainWindow)
        self.actionsave_last_calculated_spectra.setObjectName("actionsave_last_calculated_spectra")
        self.actionsave_last_calculated_mapping = QtWidgets.QAction(MainWindow)
        self.actionsave_last_calculated_mapping.setObjectName("actionsave_last_calculated_mapping")
        self.actionsave_last_calculated_rasterscan = QtWidgets.QAction(MainWindow)
        self.actionsave_last_calculated_rasterscan.setObjectName("actionsave_last_calculated_rasterscan")
        self.menusimulation.addAction(self.actionsave_sim)
        self.menusimulation.addAction(self.actionload_sim)
        self.menusimulation.addSeparator()
        self.menusimulation.addAction(self.actionsave_structure)
        self.menusimulation.addAction(self.actionsave_structure_as_txt)
        self.menusimulation.addAction(self.actionload_structure)
        self.menusave_results.addAction(self.actionsave_last_calculated_spectra)
        self.menusave_results.addAction(self.actionsave_last_calculated_mapping)
        self.menusave_results.addAction(self.actionsave_last_calculated_rasterscan)
        self.menubar.addAction(self.menusimulation.menuAction())
        self.menubar.addAction(self.menusave_results.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyGDM - GUI"))
        self.label_41.setText(_translate("MainWindow", "environment:"))
        self.label_7.setToolTip(_translate("MainWindow", "complex refractive index"))
        self.label_7.setText(_translate("MainWindow", "n1, n2, n3 "))
        self.lineEditN1.setToolTip(_translate("MainWindow", "substrate refractive index"))
        self.lineEditN1.setText(_translate("MainWindow", "1.0"))
        self.lineEditN2.setToolTip(_translate("MainWindow", "environment refractive index"))
        self.lineEditN2.setText(_translate("MainWindow", "1.0"))
        self.lineEditN3.setToolTip(_translate("MainWindow", "top cladding refractive index"))
        self.lineEditN3.setText(_translate("MainWindow", "1.0"))
        self.label_8.setText(_translate("MainWindow", "spacing (nm)"))
        self.lineEditSpacing.setToolTip(_translate("MainWindow", "thickness of layer between substrate and cladding (the nanostructre is positioned here)"))
        self.lineEditSpacing.setText(_translate("MainWindow", "5000.0"))
        self.label.setText(_translate("MainWindow", "structure config"))
        self.lineEditStep.setText(_translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "step (nm)"))
        self.label_4.setText(_translate("MainWindow", "mesh type"))
        self.label_3.setText(_translate("MainWindow", "material"))
        self.label_5.setText(_translate("MainWindow", "geometry model"))
        self.pushButtonAddGeo.setText(_translate("MainWindow", "add geometry"))
        self.label_9.setText(_translate("MainWindow", "list of constituents"))
        self.checkBoxGeoMaterialLabels.setText(_translate("MainWindow", "material labels"))
        self.pushButtonDelGeo.setText(_translate("MainWindow", "delete selected"))
        self.pushButtonClearGeo.setText(_translate("MainWindow", "clear structure"))
        self.label_29.setText(_translate("MainWindow", "move selected sub-structure:"))
        self.pushButtonOffsetXpOne.setText(_translate("MainWindow", "+X"))
        self.pushButtonOffsetXmOne.setText(_translate("MainWindow", "-X"))
        self.pushButtonOffsetYpOne.setText(_translate("MainWindow", "+Y"))
        self.pushButtonOffsetYmOne.setText(_translate("MainWindow", "-Y"))
        self.pushButtonOffsetZpOne.setText(_translate("MainWindow", "+Z"))
        self.pushButtonOffsetZmOne.setText(_translate("MainWindow", "-Z"))
        self.lineEditOffsetZ.setToolTip(_translate("MainWindow", "units of \"step\""))
        self.lineEditOffsetZ.setText(_translate("MainWindow", "0.0"))
        self.label_12.setText(_translate("MainWindow", "z:"))
        self.label_11.setText(_translate("MainWindow", "y:"))
        self.lineEditOffsetX.setToolTip(_translate("MainWindow", "units of \"step\""))
        self.lineEditOffsetX.setText(_translate("MainWindow", "0.0"))
        self.label_10.setText(_translate("MainWindow", "x:"))
        self.lineEditOffsetY.setToolTip(_translate("MainWindow", "units of \"step\""))
        self.lineEditOffsetY.setText(_translate("MainWindow", "0.0"))
        self.pushButtonApplyOffsetGeo.setText(_translate("MainWindow", "apply offset (steps)"))
        self.pushButtonApplyRotationGeo.setText(_translate("MainWindow", "apply rotation (degrees)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "geometry"))
        self.label_13.setText(_translate("MainWindow", "simulation config"))
        self.label_14.setText(_translate("MainWindow", "wl range:\n"
"(nm)"))
        self.lineEditWl0.setText(_translate("MainWindow", "500"))
        self.label_15.setText(_translate("MainWindow", " - "))
        self.lineEditWl1.setText(_translate("MainWindow", "1000"))
        self.label_16.setText(_translate("MainWindow", "N="))
        self.lineEditNwl.setText(_translate("MainWindow", "20"))
        self.label_17.setText(_translate("MainWindow", "incident field"))
        self.label_18.setText(_translate("MainWindow", "field generator:"))
        self.label_37.setText(_translate("MainWindow", "solver"))
        self.comboBoxInversionMethod.setCurrentText(_translate("MainWindow", "lu"))
        self.comboBoxInversionMethod.setItemText(0, _translate("MainWindow", "lu"))
        self.comboBoxInversionMethod.setItemText(1, _translate("MainWindow", "scipyinv"))
        self.comboBoxInversionMethod.setItemText(2, _translate("MainWindow", "cupy"))
        self.checkBoxCalcH.setText(_translate("MainWindow", "calc. H"))
        self.pushButtonStartSim.setText(_translate("MainWindow", "run simulation"))
        self.pushButtonCancelSim.setToolTip(_translate("MainWindow", "cancel running simulation (ends after the current wavelength)"))
        self.pushButtonCancelSim.setText(_translate("MainWindow", "cancel simulation"))
        self.label_19.setText(_translate("MainWindow", "status:"))
        self.label_20.setText(_translate("MainWindow", "wavelengths:"))
        self.label_21.setText(_translate("MainWindow", "field configs:"))
        self.label_22.setText(_translate("MainWindow", "selection:"))
        self.pushButtonQuicksaveSim.setText(_translate("MainWindow", "quick save sim"))
        self.pushButtonQuickloadSim.setText(_translate("MainWindow", "quick load sim"))
        self.checkBoxUpdateLatest.setText(_translate("MainWindow", "update\n"
"during sim"))
        self.label_24.setText(_translate("MainWindow", "scale"))
        self.lineEditAnimateIntFieldScale.setText(_translate("MainWindow", "1"))
        self.pushButtonToggleAnimateIntField.setText(_translate("MainWindow", "toggle animate"))
        self.label_23.setText(_translate("MainWindow", "fps:"))
        self.lineEditAnimateIntFieldfps.setText(_translate("MainWindow", "20"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>plot moment<br>in optical cycle:</p></body></html>"))
        self.radioButtonE.setText(_translate("MainWindow", "E"))
        self.radioButtonH.setText(_translate("MainWindow", "H"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_internalfields), _translate("MainWindow", "internal fields"))
        self.label_34.setText(_translate("MainWindow", "processing"))
        self.label_28.setText(_translate("MainWindow", "function"))
        self.pushButtonCalcSpectrum1.setText(_translate("MainWindow", "calculate spectrum"))
        self.label_35.setText(_translate("MainWindow", "config"))
        self.checkBoxSepPlotsSpectra.setText(_translate("MainWindow", "separate plots"))
        self.checkBoxClearPlotsSpectra.setToolTip(_translate("MainWindow", "whether to add the spectrum or plot in emtpy figure (only if not plotting in separate plots)"))
        self.checkBoxClearPlotsSpectra.setText(_translate("MainWindow", "clear figure"))
        self.pushButtonCalcSpectrum2.setText(_translate("MainWindow", "calculate spectrum"))
        self.pushButtonSaveSpec.setText(_translate("MainWindow", "save last as txt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_spectra), _translate("MainWindow", "spectra"))
        self.label_30.setText(_translate("MainWindow", "processing"))
        self.label_26.setText(_translate("MainWindow", "function"))
        self.pushButtonCalcMapping1.setText(_translate("MainWindow", "calculate mapping"))
        self.label_27.setText(_translate("MainWindow", "config"))
        self.checkBoxMappingGeoContour.setText(_translate("MainWindow", "geo contour"))
        self.checkBoxSepPlotsMapping.setText(_translate("MainWindow", "1D: separate plots"))
        self.checkBoxClearPlotsMapping.setText(_translate("MainWindow", "1D: clear plot"))
        self.pushButtonCalcMapping2.setText(_translate("MainWindow", "calculate mapping"))
        self.pushButtonSaveMapping.setText(_translate("MainWindow", "save last as txt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_mapping), _translate("MainWindow", "mappings"))
        self.label_38.setText(_translate("MainWindow", "processing"))
        self.label_32.setText(_translate("MainWindow", "x keys:"))
        self.lineEditResterscanXkey.setToolTip(_translate("MainWindow", "kwarg to use for x-scan direction. Will use first key of the comma separated list, found in field-config."))
        self.lineEditResterscanXkey.setText(_translate("MainWindow", "xSpot,x0"))
        self.label_33.setText(_translate("MainWindow", "y keys:"))
        self.lineEditResterscanYkey.setToolTip(_translate("MainWindow", "kwarg to use for y-scan direction. Will use first key of the comma separated list, found in field-config."))
        self.lineEditResterscanYkey.setText(_translate("MainWindow", "ySpot,y0"))
        self.label_31.setText(_translate("MainWindow", "field config"))
        self.label_39.setText(_translate("MainWindow", "function"))
        self.pushButtonCalcRasterscan1.setText(_translate("MainWindow", "calc. rasterscan"))
        self.label_40.setText(_translate("MainWindow", "config"))
        self.checkBoxRasterscanGeoContour.setText(_translate("MainWindow", "geo contour"))
        self.checkBoxSepPlotsRasterscan.setText(_translate("MainWindow", "1D: separate plots"))
        self.checkBoxClearPlotsRasterscan.setText(_translate("MainWindow", "1D: clear plot"))
        self.pushButtonCalcRasterscan2.setText(_translate("MainWindow", "calc. rasterscan"))
        self.pushButtonSaveRasterscan.setText(_translate("MainWindow", "save last as txt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_rasterscan), _translate("MainWindow", "rasterscan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "simulation"))
        self.menusimulation.setTitle(_translate("MainWindow", "simulation"))
        self.menusave_results.setTitle(_translate("MainWindow", "save results"))
        self.actionload_struct.setText(_translate("MainWindow", "load"))
        self.actionload_sim.setText(_translate("MainWindow", "load sim"))
        self.actionsave_sim.setText(_translate("MainWindow", "save sim"))
        self.actionsave_struct.setText(_translate("MainWindow", "save"))
        self.actionsave_structure.setText(_translate("MainWindow", "save structure"))
        self.actionload_structure.setText(_translate("MainWindow", "load structure"))
        self.actionsave_structure_as_txt.setText(_translate("MainWindow", "save structure as txt"))
        self.actionsave_structure_as_txt.setToolTip(_translate("MainWindow", "save structure as txt (coordinates only)"))
        self.actionsave_last_calculated_spectra.setText(_translate("MainWindow", "save last calculated spectra"))
        self.actionsave_last_calculated_mapping.setText(_translate("MainWindow", "save last calculated mapping"))
        self.actionsave_last_calculated_rasterscan.setText(_translate("MainWindow", "save last calculated rasterscan"))
from pygdmUI.custom_qt_objects import MayaviQWidget_NF, MayaviQWidget_geo, MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
