depends = ('ITKPyBase', 'ITKStatistics', 'ITKImageGrid', 'ITKConnectedComponents', )
templates = (
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS2SSFF', True, 'itk::VectorImage< signed short,2 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS2SSDD', True, 'itk::VectorImage< signed short,2 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS2UCFF', True, 'itk::VectorImage< signed short,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS2UCDD', True, 'itk::VectorImage< signed short,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS2USFF', True, 'itk::VectorImage< signed short,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS2USDD', True, 'itk::VectorImage< signed short,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2SSFF', True, 'itk::VectorImage< unsigned char,2 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2SSDD', True, 'itk::VectorImage< unsigned char,2 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2UCFF', True, 'itk::VectorImage< unsigned char,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2UCDD', True, 'itk::VectorImage< unsigned char,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2USFF', True, 'itk::VectorImage< unsigned char,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2USDD', True, 'itk::VectorImage< unsigned char,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2SSFF', True, 'itk::VectorImage< unsigned short,2 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2SSDD', True, 'itk::VectorImage< unsigned short,2 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2UCFF', True, 'itk::VectorImage< unsigned short,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2UCDD', True, 'itk::VectorImage< unsigned short,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2USFF', True, 'itk::VectorImage< unsigned short,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2USDD', True, 'itk::VectorImage< unsigned short,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2SSFF', True, 'itk::VectorImage< float,2 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2SSDD', True, 'itk::VectorImage< float,2 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2UCFF', True, 'itk::VectorImage< float,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2UCDD', True, 'itk::VectorImage< float,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2USFF', True, 'itk::VectorImage< float,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2USDD', True, 'itk::VectorImage< float,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2SSFF', True, 'itk::VectorImage< double,2 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2SSDD', True, 'itk::VectorImage< double,2 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2UCFF', True, 'itk::VectorImage< double,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2UCDD', True, 'itk::VectorImage< double,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2USFF', True, 'itk::VectorImage< double,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2USDD', True, 'itk::VectorImage< double,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS3SSFF', True, 'itk::VectorImage< signed short,3 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS3SSDD', True, 'itk::VectorImage< signed short,3 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS3UCFF', True, 'itk::VectorImage< signed short,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS3UCDD', True, 'itk::VectorImage< signed short,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS3USFF', True, 'itk::VectorImage< signed short,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS3USDD', True, 'itk::VectorImage< signed short,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3SSFF', True, 'itk::VectorImage< unsigned char,3 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3SSDD', True, 'itk::VectorImage< unsigned char,3 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3UCFF', True, 'itk::VectorImage< unsigned char,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3UCDD', True, 'itk::VectorImage< unsigned char,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3USFF', True, 'itk::VectorImage< unsigned char,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3USDD', True, 'itk::VectorImage< unsigned char,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3SSFF', True, 'itk::VectorImage< unsigned short,3 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3SSDD', True, 'itk::VectorImage< unsigned short,3 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3UCFF', True, 'itk::VectorImage< unsigned short,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3UCDD', True, 'itk::VectorImage< unsigned short,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3USFF', True, 'itk::VectorImage< unsigned short,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3USDD', True, 'itk::VectorImage< unsigned short,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3SSFF', True, 'itk::VectorImage< float,3 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3SSDD', True, 'itk::VectorImage< float,3 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3UCFF', True, 'itk::VectorImage< float,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3UCDD', True, 'itk::VectorImage< float,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3USFF', True, 'itk::VectorImage< float,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3USDD', True, 'itk::VectorImage< float,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3SSFF', True, 'itk::VectorImage< double,3 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3SSDD', True, 'itk::VectorImage< double,3 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3UCFF', True, 'itk::VectorImage< double,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3UCDD', True, 'itk::VectorImage< double,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3USFF', True, 'itk::VectorImage< double,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3USDD', True, 'itk::VectorImage< double,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS4SSFF', True, 'itk::VectorImage< signed short,4 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS4SSDD', True, 'itk::VectorImage< signed short,4 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS4UCFF', True, 'itk::VectorImage< signed short,4 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS4UCDD', True, 'itk::VectorImage< signed short,4 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS4USFF', True, 'itk::VectorImage< signed short,4 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVISS4USDD', True, 'itk::VectorImage< signed short,4 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC4SSFF', True, 'itk::VectorImage< unsigned char,4 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC4SSDD', True, 'itk::VectorImage< unsigned char,4 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC4UCFF', True, 'itk::VectorImage< unsigned char,4 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC4UCDD', True, 'itk::VectorImage< unsigned char,4 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC4USFF', True, 'itk::VectorImage< unsigned char,4 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC4USDD', True, 'itk::VectorImage< unsigned char,4 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS4SSFF', True, 'itk::VectorImage< unsigned short,4 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS4SSDD', True, 'itk::VectorImage< unsigned short,4 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS4UCFF', True, 'itk::VectorImage< unsigned short,4 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS4UCDD', True, 'itk::VectorImage< unsigned short,4 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS4USFF', True, 'itk::VectorImage< unsigned short,4 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS4USDD', True, 'itk::VectorImage< unsigned short,4 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF4SSFF', True, 'itk::VectorImage< float,4 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF4SSDD', True, 'itk::VectorImage< float,4 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF4UCFF', True, 'itk::VectorImage< float,4 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF4UCDD', True, 'itk::VectorImage< float,4 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF4USFF', True, 'itk::VectorImage< float,4 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF4USDD', True, 'itk::VectorImage< float,4 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID4SSFF', True, 'itk::VectorImage< double,4 >, signed short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID4SSDD', True, 'itk::VectorImage< double,4 >, signed short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID4UCFF', True, 'itk::VectorImage< double,4 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID4UCDD', True, 'itk::VectorImage< double,4 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID4USFF', True, 'itk::VectorImage< double,4 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID4USDD', True, 'itk::VectorImage< double,4 >, unsigned short, double, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterISS2F', True, 'itk::Image< signed short,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterISS2D', True, 'itk::Image< signed short,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC2F', True, 'itk::Image< unsigned char,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC2D', True, 'itk::Image< unsigned char,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS2F', True, 'itk::Image< unsigned short,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS2D', True, 'itk::Image< unsigned short,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF2F', True, 'itk::Image< float,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF2D', True, 'itk::Image< float,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID2F', True, 'itk::Image< double,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID2D', True, 'itk::Image< double,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterISS3F', True, 'itk::Image< signed short,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterISS3D', True, 'itk::Image< signed short,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC3F', True, 'itk::Image< unsigned char,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC3D', True, 'itk::Image< unsigned char,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS3F', True, 'itk::Image< unsigned short,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS3D', True, 'itk::Image< unsigned short,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF3F', True, 'itk::Image< float,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF3D', True, 'itk::Image< float,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID3F', True, 'itk::Image< double,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID3D', True, 'itk::Image< double,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterISS4F', True, 'itk::Image< signed short,4 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterISS4D', True, 'itk::Image< signed short,4 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC4F', True, 'itk::Image< unsigned char,4 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC4D', True, 'itk::Image< unsigned char,4 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS4F', True, 'itk::Image< unsigned short,4 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS4D', True, 'itk::Image< unsigned short,4 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF4F', True, 'itk::Image< float,4 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF4D', True, 'itk::Image< float,4 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID4F', True, 'itk::Image< double,4 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID4D', True, 'itk::Image< double,4 >, double'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS4IUC4', True, 'itk::Image< signed short,4 >, itk::Image< unsigned char,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS2IUS2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS3IUS3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterISS4IUS4', True, 'itk::Image< signed short,4 >, itk::Image< unsigned short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC4ISS4', True, 'itk::Image< unsigned char,4 >, itk::Image< signed short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC2IUS2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC3IUS3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC4IUS4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS2ISS2', True, 'itk::Image< unsigned short,2 >, itk::Image< signed short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS3ISS3', True, 'itk::Image< unsigned short,3 >, itk::Image< signed short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS4ISS4', True, 'itk::Image< unsigned short,4 >, itk::Image< signed short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS2IUC2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS3IUC3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS4IUC4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned char,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF4ISS4', True, 'itk::Image< float,4 >, itk::Image< signed short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF4IUC4', True, 'itk::Image< float,4 >, itk::Image< unsigned char,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF2IUS2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF3IUS3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF4IUS4', True, 'itk::Image< float,4 >, itk::Image< unsigned short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID2ISS2', True, 'itk::Image< double,2 >, itk::Image< signed short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID3ISS3', True, 'itk::Image< double,3 >, itk::Image< signed short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID4ISS4', True, 'itk::Image< double,4 >, itk::Image< signed short,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID2IUC2', True, 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID3IUC3', True, 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID4IUC4', True, 'itk::Image< double,4 >, itk::Image< unsigned char,4 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID2IUS2', True, 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID3IUS3', True, 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID4IUS4', True, 'itk::Image< double,4 >, itk::Image< unsigned short,4 >'),
)
