# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1vQUWrUlsGGxwBubikt6GSlUrfVvZDI
"""

from setuptools import setup

with open("README.rtf","r") as fh:
    long_description = fh.read()

setup(
    name='ColBertPyterrier',
    version = '0.0.1',
    description='ColBert integrated with Pyterrier',
    long_desciption=long_description,
    long_discription_content_type="text/markdown",
    py_modules=["ColBertPyterrier","createcollection","setretrieve","treccreatecollection"],
    package_dir={'':'src'},
    classifiers=[
        "Programming Language :: Python :: 3.6",
        "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
        "Operating System :: OS Independent"
    ],
    url="https://github.com/SanjanaKarumuri/ColBertPyterrier",
    author="Sanjana Karumuri",
    author_email="2309591k@student.gla.ac.uk"
        
        

)
