# Generated by Django 2.2.4 on 2020-04-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0005_auto_20200430_0520'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cfdi',
            table='cfdi_cfdi',
        ),
    ]
