# Generated by Django 2.2.16 on 2020-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_cashnet', '0004_auto_20200902_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
