
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-03T21:13:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf467df39f2d3684bc8bb236a91fc77a676947a1",
 "version": "0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
