depends = ('ITKPyBase', 'ITKStatistics', 'ITKImageSources', 'ITKImageGrid', 'ITKCommon', )
templates = (
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS2IULL2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS3IULL3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS4IULL4', True, 'itk::Image< signed short,4 >, itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS2IUS2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS3IUS3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterISS4IUS4', True, 'itk::Image< signed short,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC2IULL2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC3IULL3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC4IULL4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC2IUS2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC3IUS3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUC4IUS4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS2IULL2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS3IULL3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS4IULL4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF2IULL2', True, 'itk::Image< float,2 >, itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF3IULL3', True, 'itk::Image< float,3 >, itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF4IULL4', True, 'itk::Image< float,4 >, itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF2IUS2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF3IUS3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIF4IUS4', True, 'itk::Image< float,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID2IULL2', True, 'itk::Image< double,2 >, itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID3IULL3', True, 'itk::Image< double,3 >, itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID4IULL4', True, 'itk::Image< double,4 >, itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID2IUS2', True, 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID3IUS3', True, 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterID4IUS4', True, 'itk::Image< double,4 >, itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS2IULL2', True, 'itk::VectorImage< signed short,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS2IUS2', True, 'itk::VectorImage< signed short,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC2IULL2', True, 'itk::VectorImage< unsigned char,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC2IULL2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC2IUS2', True, 'itk::VectorImage< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC2IUS2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS2IULL2', True, 'itk::VectorImage< unsigned short,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS2IUS2', True, 'itk::VectorImage< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF2IULL2', True, 'itk::VectorImage< float,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF22IULL2', True, 'itk::Image< itk::Vector< float,2 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF22IULL2', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF32IULL2', True, 'itk::Image< itk::Vector< float,3 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF32IULL2', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF42IULL2', True, 'itk::Image< itk::Vector< float,4 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF42IULL2', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF2IUS2', True, 'itk::VectorImage< float,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF22IUS2', True, 'itk::Image< itk::Vector< float,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF22IUS2', True, 'itk::Image< itk::CovariantVector< float,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF32IUS2', True, 'itk::Image< itk::Vector< float,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF32IUS2', True, 'itk::Image< itk::CovariantVector< float,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF42IUS2', True, 'itk::Image< itk::Vector< float,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF42IUS2', True, 'itk::Image< itk::CovariantVector< float,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID2IULL2', True, 'itk::VectorImage< double,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD22IULL2', True, 'itk::Image< itk::Vector< double,2 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD22IULL2', True, 'itk::Image< itk::CovariantVector< double,2 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD32IULL2', True, 'itk::Image< itk::Vector< double,3 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD32IULL2', True, 'itk::Image< itk::CovariantVector< double,3 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD42IULL2', True, 'itk::Image< itk::Vector< double,4 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD42IULL2', True, 'itk::Image< itk::CovariantVector< double,4 >,2 >,itk::Image< unsigned long long,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID2IUS2', True, 'itk::VectorImage< double,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD22IUS2', True, 'itk::Image< itk::Vector< double,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD22IUS2', True, 'itk::Image< itk::CovariantVector< double,2 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD32IUS2', True, 'itk::Image< itk::Vector< double,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD32IUS2', True, 'itk::Image< itk::CovariantVector< double,3 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD42IUS2', True, 'itk::Image< itk::Vector< double,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD42IUS2', True, 'itk::Image< itk::CovariantVector< double,4 >,2 >,itk::Image< unsigned short,2 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS3IULL3', True, 'itk::VectorImage< signed short,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS3IUS3', True, 'itk::VectorImage< signed short,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC3IULL3', True, 'itk::VectorImage< unsigned char,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC3IULL3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC3IUS3', True, 'itk::VectorImage< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC3IUS3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS3IULL3', True, 'itk::VectorImage< unsigned short,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS3IUS3', True, 'itk::VectorImage< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF3IULL3', True, 'itk::VectorImage< float,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF23IULL3', True, 'itk::Image< itk::Vector< float,2 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF23IULL3', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF33IULL3', True, 'itk::Image< itk::Vector< float,3 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF33IULL3', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF43IULL3', True, 'itk::Image< itk::Vector< float,4 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF43IULL3', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF3IUS3', True, 'itk::VectorImage< float,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF23IUS3', True, 'itk::Image< itk::Vector< float,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF23IUS3', True, 'itk::Image< itk::CovariantVector< float,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF33IUS3', True, 'itk::Image< itk::Vector< float,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF33IUS3', True, 'itk::Image< itk::CovariantVector< float,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF43IUS3', True, 'itk::Image< itk::Vector< float,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF43IUS3', True, 'itk::Image< itk::CovariantVector< float,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID3IULL3', True, 'itk::VectorImage< double,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD23IULL3', True, 'itk::Image< itk::Vector< double,2 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD23IULL3', True, 'itk::Image< itk::CovariantVector< double,2 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD33IULL3', True, 'itk::Image< itk::Vector< double,3 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD33IULL3', True, 'itk::Image< itk::CovariantVector< double,3 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD43IULL3', True, 'itk::Image< itk::Vector< double,4 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD43IULL3', True, 'itk::Image< itk::CovariantVector< double,4 >,3 >,itk::Image< unsigned long long,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID3IUS3', True, 'itk::VectorImage< double,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD23IUS3', True, 'itk::Image< itk::Vector< double,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD23IUS3', True, 'itk::Image< itk::CovariantVector< double,2 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD33IUS3', True, 'itk::Image< itk::Vector< double,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD33IUS3', True, 'itk::Image< itk::CovariantVector< double,3 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD43IUS3', True, 'itk::Image< itk::Vector< double,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD43IUS3', True, 'itk::Image< itk::CovariantVector< double,4 >,3 >,itk::Image< unsigned short,3 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS4IULL4', True, 'itk::VectorImage< signed short,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVISS4IUS4', True, 'itk::VectorImage< signed short,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC4IULL4', True, 'itk::VectorImage< unsigned char,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC4IULL4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUC4IUS4', True, 'itk::VectorImage< unsigned char,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIRGBUC4IUS4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS4IULL4', True, 'itk::VectorImage< unsigned short,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIUS4IUS4', True, 'itk::VectorImage< unsigned short,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF4IULL4', True, 'itk::VectorImage< float,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF24IULL4', True, 'itk::Image< itk::Vector< float,2 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF24IULL4', True, 'itk::Image< itk::CovariantVector< float,2 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF34IULL4', True, 'itk::Image< itk::Vector< float,3 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF34IULL4', True, 'itk::Image< itk::CovariantVector< float,3 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF44IULL4', True, 'itk::Image< itk::Vector< float,4 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF44IULL4', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVIF4IUS4', True, 'itk::VectorImage< float,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF24IUS4', True, 'itk::Image< itk::Vector< float,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF24IUS4', True, 'itk::Image< itk::CovariantVector< float,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF34IUS4', True, 'itk::Image< itk::Vector< float,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF34IUS4', True, 'itk::Image< itk::CovariantVector< float,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVF44IUS4', True, 'itk::Image< itk::Vector< float,4 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVF44IUS4', True, 'itk::Image< itk::CovariantVector< float,4 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID4IULL4', True, 'itk::VectorImage< double,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD24IULL4', True, 'itk::Image< itk::Vector< double,2 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD24IULL4', True, 'itk::Image< itk::CovariantVector< double,2 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD34IULL4', True, 'itk::Image< itk::Vector< double,3 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD34IULL4', True, 'itk::Image< itk::CovariantVector< double,3 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD44IULL4', True, 'itk::Image< itk::Vector< double,4 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD44IULL4', True, 'itk::Image< itk::CovariantVector< double,4 >,4 >,itk::Image< unsigned long long,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterVID4IUS4', True, 'itk::VectorImage< double,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD24IUS4', True, 'itk::Image< itk::Vector< double,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD24IUS4', True, 'itk::Image< itk::CovariantVector< double,2 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD34IUS4', True, 'itk::Image< itk::Vector< double,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD34IUS4', True, 'itk::Image< itk::CovariantVector< double,3 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterIVD44IUS4', True, 'itk::Image< itk::Vector< double,4 >,4 >,itk::Image< unsigned short,4 >'),
  ('SLICImageFilter', 'itk::SLICImageFilter', 'itkSLICImageFilterICVD44IUS4', True, 'itk::Image< itk::CovariantVector< double,4 >,4 >,itk::Image< unsigned short,4 >'),
)
