"""
    Diahook

    The Diahook server API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import diahook.openapi_client
from diahook.openapi_client.model.endpoint_in import EndpointIn


class TestEndpointIn(unittest.TestCase):
    """EndpointIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointIn(self):
        """Test EndpointIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndpointIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
