# coding: utf-8

"""
    Assetic Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BackgroundWorkerStatusRepresentation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'document_id': 'str',
        'requested_time': 'datetime',
        'start_time': 'datetime',
        'end_time': 'datetime'
    }

    attribute_map = {
        'status': 'Status',
        'document_id': 'DocumentId',
        'requested_time': 'RequestedTime',
        'start_time': 'StartTime',
        'end_time': 'EndTime'
    }

    def __init__(self, status=None, document_id=None, requested_time=None, start_time=None, end_time=None):  # noqa: E501
        """BackgroundWorkerStatusRepresentation - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._document_id = None
        self._requested_time = None
        self._start_time = None
        self._end_time = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if document_id is not None:
            self.document_id = document_id
        if requested_time is not None:
            self.requested_time = requested_time
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time

    @property
    def status(self):
        """Gets the status of this BackgroundWorkerStatusRepresentation.  # noqa: E501


        :return: The status of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BackgroundWorkerStatusRepresentation.


        :param status: The status of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def document_id(self):
        """Gets the document_id of this BackgroundWorkerStatusRepresentation.  # noqa: E501


        :return: The document_id of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this BackgroundWorkerStatusRepresentation.


        :param document_id: The document_id of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :type: str
        """

        self._document_id = document_id

    @property
    def requested_time(self):
        """Gets the requested_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501


        :return: The requested_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :rtype: datetime
        """
        return self._requested_time

    @requested_time.setter
    def requested_time(self, requested_time):
        """Sets the requested_time of this BackgroundWorkerStatusRepresentation.


        :param requested_time: The requested_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :type: datetime
        """

        self._requested_time = requested_time

    @property
    def start_time(self):
        """Gets the start_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501


        :return: The start_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this BackgroundWorkerStatusRepresentation.


        :param start_time: The start_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501


        :return: The end_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this BackgroundWorkerStatusRepresentation.


        :param end_time: The end_time of this BackgroundWorkerStatusRepresentation.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BackgroundWorkerStatusRepresentation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BackgroundWorkerStatusRepresentation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
