# coding: utf-8

"""
    Assetic Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

##from assetic.models.embedded_resource import EmbeddedResource  # noqa: F401,E501
##from assetic.models.link import Link  # noqa: F401,E501


class ConfigUnitType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'singular_name': 'str',
        'plural_name': 'str',
        'description': 'str',
        'is_default': 'bool',
        'links': 'list[Link]',
        'embedded': 'list[EmbeddedResource]'
    }

    attribute_map = {
        'id': 'Id',
        'singular_name': 'SingularName',
        'plural_name': 'PluralName',
        'description': 'Description',
        'is_default': 'IsDefault',
        'links': '_links',
        'embedded': '_embedded'
    }

    def __init__(self, id=None, singular_name=None, plural_name=None, description=None, is_default=None, links=None, embedded=None):  # noqa: E501
        """ConfigUnitType - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._singular_name = None
        self._plural_name = None
        self._description = None
        self._is_default = None
        self._links = None
        self._embedded = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if singular_name is not None:
            self.singular_name = singular_name
        if plural_name is not None:
            self.plural_name = plural_name
        if description is not None:
            self.description = description
        if is_default is not None:
            self.is_default = is_default
        if links is not None:
            self.links = links
        if embedded is not None:
            self.embedded = embedded

    @property
    def id(self):
        """Gets the id of this ConfigUnitType.  # noqa: E501


        :return: The id of this ConfigUnitType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConfigUnitType.


        :param id: The id of this ConfigUnitType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def singular_name(self):
        """Gets the singular_name of this ConfigUnitType.  # noqa: E501


        :return: The singular_name of this ConfigUnitType.  # noqa: E501
        :rtype: str
        """
        return self._singular_name

    @singular_name.setter
    def singular_name(self, singular_name):
        """Sets the singular_name of this ConfigUnitType.


        :param singular_name: The singular_name of this ConfigUnitType.  # noqa: E501
        :type: str
        """

        self._singular_name = singular_name

    @property
    def plural_name(self):
        """Gets the plural_name of this ConfigUnitType.  # noqa: E501


        :return: The plural_name of this ConfigUnitType.  # noqa: E501
        :rtype: str
        """
        return self._plural_name

    @plural_name.setter
    def plural_name(self, plural_name):
        """Sets the plural_name of this ConfigUnitType.


        :param plural_name: The plural_name of this ConfigUnitType.  # noqa: E501
        :type: str
        """

        self._plural_name = plural_name

    @property
    def description(self):
        """Gets the description of this ConfigUnitType.  # noqa: E501


        :return: The description of this ConfigUnitType.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConfigUnitType.


        :param description: The description of this ConfigUnitType.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_default(self):
        """Gets the is_default of this ConfigUnitType.  # noqa: E501


        :return: The is_default of this ConfigUnitType.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this ConfigUnitType.


        :param is_default: The is_default of this ConfigUnitType.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def links(self):
        """Gets the links of this ConfigUnitType.  # noqa: E501


        :return: The links of this ConfigUnitType.  # noqa: E501
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ConfigUnitType.


        :param links: The links of this ConfigUnitType.  # noqa: E501
        :type: list[Link]
        """

        self._links = links

    @property
    def embedded(self):
        """Gets the embedded of this ConfigUnitType.  # noqa: E501


        :return: The embedded of this ConfigUnitType.  # noqa: E501
        :rtype: list[EmbeddedResource]
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this ConfigUnitType.


        :param embedded: The embedded of this ConfigUnitType.  # noqa: E501
        :type: list[EmbeddedResource]
        """

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigUnitType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigUnitType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
