# coding: utf-8

"""
    Assetic Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

##from assetic.models.embedded_resource import EmbeddedResource  # noqa: F401,E501
##from assetic.models.link import Link  # noqa: F401,E501


class InterruptionFactor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'interruption_factor_name': 'str',
        'interruption_factor_id': 'str',
        'description': 'str',
        'links': 'list[Link]',
        'embedded': 'list[EmbeddedResource]'
    }

    attribute_map = {
        'id': 'Id',
        'interruption_factor_name': 'InterruptionFactorName',
        'interruption_factor_id': 'InterruptionFactorID',
        'description': 'Description',
        'links': '_links',
        'embedded': '_embedded'
    }

    def __init__(self, id=None, interruption_factor_name=None, interruption_factor_id=None, description=None, links=None, embedded=None):  # noqa: E501
        """InterruptionFactor - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._interruption_factor_name = None
        self._interruption_factor_id = None
        self._description = None
        self._links = None
        self._embedded = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if interruption_factor_name is not None:
            self.interruption_factor_name = interruption_factor_name
        if interruption_factor_id is not None:
            self.interruption_factor_id = interruption_factor_id
        if description is not None:
            self.description = description
        if links is not None:
            self.links = links
        if embedded is not None:
            self.embedded = embedded

    @property
    def id(self):
        """Gets the id of this InterruptionFactor.  # noqa: E501


        :return: The id of this InterruptionFactor.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InterruptionFactor.


        :param id: The id of this InterruptionFactor.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def interruption_factor_name(self):
        """Gets the interruption_factor_name of this InterruptionFactor.  # noqa: E501


        :return: The interruption_factor_name of this InterruptionFactor.  # noqa: E501
        :rtype: str
        """
        return self._interruption_factor_name

    @interruption_factor_name.setter
    def interruption_factor_name(self, interruption_factor_name):
        """Sets the interruption_factor_name of this InterruptionFactor.


        :param interruption_factor_name: The interruption_factor_name of this InterruptionFactor.  # noqa: E501
        :type: str
        """

        self._interruption_factor_name = interruption_factor_name

    @property
    def interruption_factor_id(self):
        """Gets the interruption_factor_id of this InterruptionFactor.  # noqa: E501


        :return: The interruption_factor_id of this InterruptionFactor.  # noqa: E501
        :rtype: str
        """
        return self._interruption_factor_id

    @interruption_factor_id.setter
    def interruption_factor_id(self, interruption_factor_id):
        """Sets the interruption_factor_id of this InterruptionFactor.


        :param interruption_factor_id: The interruption_factor_id of this InterruptionFactor.  # noqa: E501
        :type: str
        """

        self._interruption_factor_id = interruption_factor_id

    @property
    def description(self):
        """Gets the description of this InterruptionFactor.  # noqa: E501


        :return: The description of this InterruptionFactor.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InterruptionFactor.


        :param description: The description of this InterruptionFactor.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def links(self):
        """Gets the links of this InterruptionFactor.  # noqa: E501


        :return: The links of this InterruptionFactor.  # noqa: E501
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this InterruptionFactor.


        :param links: The links of this InterruptionFactor.  # noqa: E501
        :type: list[Link]
        """

        self._links = links

    @property
    def embedded(self):
        """Gets the embedded of this InterruptionFactor.  # noqa: E501


        :return: The embedded of this InterruptionFactor.  # noqa: E501
        :rtype: list[EmbeddedResource]
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this InterruptionFactor.


        :param embedded: The embedded of this InterruptionFactor.  # noqa: E501
        :type: list[EmbeddedResource]
        """

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterruptionFactor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterruptionFactor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
