# coding: utf-8

"""
    Assetic Integration API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

##from assetic.models.custom_address import CustomAddress  # noqa: F401,E501
##from assetic.models.embedded_resource import EmbeddedResource  # noqa: F401,E501
##from assetic.models.link import Link  # noqa: F401,E501


class RequestorPhysicalLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_id': 'str',
        'address': 'CustomAddress',
        'other_location': 'str',
        'where_location': 'str',
        'links': 'list[Link]',
        'embedded': 'list[EmbeddedResource]'
    }

    attribute_map = {
        'resource_id': 'ResourceId',
        'address': 'Address',
        'other_location': 'OtherLocation',
        'where_location': 'WhereLocation',
        'links': '_links',
        'embedded': '_embedded'
    }

    def __init__(self, resource_id=None, address=None, other_location=None, where_location=None, links=None, embedded=None):  # noqa: E501
        """RequestorPhysicalLocation - a model defined in Swagger"""  # noqa: E501

        self._resource_id = None
        self._address = None
        self._other_location = None
        self._where_location = None
        self._links = None
        self._embedded = None
        self.discriminator = None

        if resource_id is not None:
            self.resource_id = resource_id
        if address is not None:
            self.address = address
        if other_location is not None:
            self.other_location = other_location
        if where_location is not None:
            self.where_location = where_location
        if links is not None:
            self.links = links
        if embedded is not None:
            self.embedded = embedded

    @property
    def resource_id(self):
        """Gets the resource_id of this RequestorPhysicalLocation.  # noqa: E501


        :return: The resource_id of this RequestorPhysicalLocation.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this RequestorPhysicalLocation.


        :param resource_id: The resource_id of this RequestorPhysicalLocation.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    @property
    def address(self):
        """Gets the address of this RequestorPhysicalLocation.  # noqa: E501


        :return: The address of this RequestorPhysicalLocation.  # noqa: E501
        :rtype: CustomAddress
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this RequestorPhysicalLocation.


        :param address: The address of this RequestorPhysicalLocation.  # noqa: E501
        :type: CustomAddress
        """

        self._address = address

    @property
    def other_location(self):
        """Gets the other_location of this RequestorPhysicalLocation.  # noqa: E501


        :return: The other_location of this RequestorPhysicalLocation.  # noqa: E501
        :rtype: str
        """
        return self._other_location

    @other_location.setter
    def other_location(self, other_location):
        """Sets the other_location of this RequestorPhysicalLocation.


        :param other_location: The other_location of this RequestorPhysicalLocation.  # noqa: E501
        :type: str
        """

        self._other_location = other_location

    @property
    def where_location(self):
        """Gets the where_location of this RequestorPhysicalLocation.  # noqa: E501


        :return: The where_location of this RequestorPhysicalLocation.  # noqa: E501
        :rtype: str
        """
        return self._where_location

    @where_location.setter
    def where_location(self, where_location):
        """Sets the where_location of this RequestorPhysicalLocation.


        :param where_location: The where_location of this RequestorPhysicalLocation.  # noqa: E501
        :type: str
        """

        self._where_location = where_location

    @property
    def links(self):
        """Gets the links of this RequestorPhysicalLocation.  # noqa: E501


        :return: The links of this RequestorPhysicalLocation.  # noqa: E501
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this RequestorPhysicalLocation.


        :param links: The links of this RequestorPhysicalLocation.  # noqa: E501
        :type: list[Link]
        """

        self._links = links

    @property
    def embedded(self):
        """Gets the embedded of this RequestorPhysicalLocation.  # noqa: E501


        :return: The embedded of this RequestorPhysicalLocation.  # noqa: E501
        :rtype: list[EmbeddedResource]
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this RequestorPhysicalLocation.


        :param embedded: The embedded of this RequestorPhysicalLocation.  # noqa: E501
        :type: list[EmbeddedResource]
        """

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RequestorPhysicalLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RequestorPhysicalLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
