MODULE_VALUES = {
    "Accounting": "Accounting",
    "Assessments": "Assessment",
    "Asset Meters": "AssetMeters",
    "Assets": "Assets",
    "Assets Associations": "Association",
    "Assets Configuration": "AssetConfiguration",
    "Components": "AssetComponent",
    "Components Network Measure": "NetworkMeasure",
    "Functional Locations": "GroupAssets",
    "Maintenance": "MaintenanceAndCategory",
    "Maintenance Configuration": "MaintenanceConfiguration",
    "Mapping": "Mapping",
    "Materials": "Material",
    "Simple Asset": "SimpleAsset",
    "Simple Asset Groups": "NetworkEntity",
    "User Management": "UserManagement",
    "Workflow": "Workflow"
}
ASSET_VALUES = {
    "Access Platforms": "AccessPlatforms",
    "Airport Buildings": "AirportBuilding",
    "Airport Plant and Equipment": "AirportPlantandEquipment",
    "Anchors": "Anchors",
    "Artworks": "Artworks",
    "Basins": "Basins",
    "Bins": "Bins",
    "Boardwalks": "OpenSpacePathways",
    "Bores and Wells": "Bores",
    "Bridges": "Bridges",
    "Buildings": "Buildings",
    "Buildings (Market Value)": "BuildingsMarketValue",
    "Buildings Equipment and Furniture": "EquipmentAndFurniture",
    "Buildings Functional Spaces": "BuildingsFunctionalSpaces",
    "Buildings Infrastructure": "BuildingsInfrastructure",
    "Car Parks": "CarParks",
    "Catchment": "Catchment",
    "Chemical Structures": "ChemicalStructures",
    "Civil Assets": "Civil",
    "Compressors": "AirCompressor",
    "Control Systems": "ControlSystems",
    "Cranes": "Cranes",
    "Creeks": "Creeks",
    "Crossing Protection": "RailwayCrossingProtection",
    "Culverts": "Culverts",
    "Detection": "RailwayDetection",
    "Dolphin Structures": "DolphinStructures",
    "Education Buildings": "EDUBuildings",
    "Education Buildings Functional Spaces": "EDUBuildingsFunctionalSpaces",
    "Electrical": "ElectricalComponants",
    "Electrical Conduit Pits": "ConduitPits",
    "Electrical Conduits": "Conduit",
    "Emergency Markers": "EmergencyMarkers",
    "Emergency Routes": "EmergencyRoute",
    "Facility": "Facility",
    "Fences": "Fences",
    "Fleet": "Fleet",
    "Fleet, Plant and Equipment": "FleetPlantAndEquipment",
    "Formal Areas": "ParkFormalAssets",
    "Gates": "Gates",
    "Generators": "Generator",
    "Hard Surfaces": "HousingHardSurfaces",
    "Heavy Fleet": "HeavyFleet",
    "High Voltage Lines": "HighVoltageLine",
    "High Voltage Poles": "HighVoltagePole",
    "Housing Buildings": "HousingBuildings",
    "Housing Functional Spaces": "HousingFunctionalSpaces",
    "Housing Landscaping": "HousingLandscaping",
    "Housing Other Structures": "HousingOtherStructures",
    "Housing Site": "HousingSite",
    "ICT Hardware": "ICT",
    "Infiltration Devices": "InfiltrationDevice",
    "Instrumentation": "Instrumentation",
    "Intersections": "IntersectionRoads",
    "Irrigation": "Irrigation",
    "Irrigation Channels": "IrrigationChannel",
    "Irrigation Regulators": "IrrigationRegulators",
    "Irrigation Sprinklers": "Sprinklers",
    "Jetties": "Jetties",
    "Kerbs": "Kerbs",
    "Kerbs (Auxiliary)": "KerbsAndPits",
    "Lagoons": "Lagoon",
    "Land": "Land",
    "Landfill Cells": "LandfillCells",
    "Landfill Lagoons": "LandfillLagoon",
    "Levee Banks": "Leveebanks",
    "Lifting Equipment": "LiftingEquipment",
    "Lighting": "StreetLighting",
    "Low Voltage Lines": "LowVoltageLine",
    "Low Voltage Poles": "LowVoltagePole",
    "Major Plant and Equipment": "BuildingsPlantAndEquipment",
    "Marine Structures": "MarineStructures",
    "Mechanical": "Mechanical",
    "Minor Plant and Equipment": "EquipmentAndPlant",
    "Municipal Heritage": "MunicipalHeritage",
    "Noise Walls": "NoiseWalls",
    "Open Drains and Rain Gardens": "OpenDrains",
    "Open Space Furniture": "OpenSpaceFurniture",
    "Open Space Service Lines": "OpenSpaceServiceLine",
    "Open Space Services": "OpenSpaceService",
    "Other Structures": "OtherStructures",
    "Park Active Areas": "ParkActiveAreas",
    "Park Infrastructure": "ParkInfrastructure",
    "Park Passive Areas": "ParkPassiveAreas",
    "Park Site": "ParkSite",
    "Parks and Gardens": "Parks",
    "Pathways": "Pathways",
    "Pathways (Auxiliary)": "Footpaths",
    "Platform": "RailwayPlatform",
    "Play Equipment": "PlayEquipment",
    "Playground Site": "PlaygroundSite",
    "Playgrounds": "Playgrounds",
    "Point Mechanism": "RailwayPointMechanism",
    "Pool Structures": "PoolStructures",
    "Port Navigation Aids": "PortNavigationAids",
    "Port Navigation Equipment": "PortNavigationEquipment",
    "Port Piers": "PortPiers",
    "Port Stacking Areas": "PortStackingareas",
    "Port Utility Services": "PortUtilityservices",
    "Property": "Property",
    "Public Transport Shelters": "BusShelters",
    "Public Transport Stops": "BusStop",
    "Rail Junctions": "RailJunction",
    "Retaining Walls": "RetainingWalls",
    "Riverbanks": "Riverbanks",
    "Road Barriers": "Barriers",
    "Road Elements": "SealedElements",
    "Roads": "SealedRoads",
    "Roads (Auxiliary)": "SealedRoadsIRIS",
    "Roads Equipment": "EquipmentRoads",
    "Runways": "Runways",
    "Sewer Fittings": "SewerFittings",
    "Sewer Low Pressure Pipes": "SewerageLowPressure",
    "Sewer Mains": "SewerMains",
    "Sewer Nodes": "SewerManholes",
    "Sewer Pits and Wells": "SewerPits",
    "Sewer Plant and Equipment": "SewerPlantAndEquipment",
    "Sewer Plant and Equipment (Auxiliary)": "EquipmentSewerage",
    "Sewer Pressure Pipes": "Sewerage",
    "Sewer Pressure Pipes (Auxiliary)": "SewerageRising",
    "Sewer Pump Stations": "SewerageEquipmentAndCivil",
    "Sewer Pumps": "SeweragePumps",
    "Sewer Services": "SewerServices",
    "Sewer Treatment Facility": "SewerTreatFacility",
    "Sewer Treatment Systems": "SewerTreatmentSystems",
    "Sewer Valves": "SewerValves",
    "Signage": "Signage",
    "Signals": "Signals",
    "Signs": "Signs",
    "Steps": "Steps",
    "Storage Structures": "StorageStructure",
    "Stormwater Drains": "Drains",
    "Stormwater End Structures": "SWEndStructures",
    "Stormwater Fittings": "SWFittings",
    "Stormwater GPTs": "GPT",
    "Stormwater Pits": "Pits",
    "Stormwater Property Connections": "SWPropertyConnection",
    "Street Furniture": "StreetFurniture",
    "Street Trees": "StreetTrees",
    "Structures": "Structures",
    "Substations": "Substation",
    "Switchboards": "SwitchBoard",
    "Switches": "Switches",
    "Table Drains": "TableDrain",
    "Track": "Railway",
    "Track Control Systems": "RailControlSystem",
    "Track Foundation": "RailwayTrackFoundation",
    "Track Points and Crossings": "RailCrossing",
    "Track Signals": "RailSignal",
    "Traffic Management Devices": "TrafficMgmtDevices",
    "Train Stops": "RailwayTrainStops",
    "Transformers": "Transformers",
    "Trees": "OpenSpaceTrees",
    "Unsealed Roads": "UnsealedRoads",
    "Water Dams": "WaterDams",
    "Water Fittings": "WaterFittings",
    "Water Hydrants": "WaterHydrants",
    "Water Meters and Services": "WaterMetersAndService",
    "Water Nodes": "WaterManholes",
    "Water Pits": "WaterPits",
    "Water Plant and Equipment": "WaterPlantAndEquipment",
    "Water Plant and Equipment (Auxiliary)": "EquipmentWater",
    "Water Pressure Pipes": "WaterMains",
    "Water Pump Stations": "WaterEquipmentAndCivil",
    "Water Pumps": "WaterPumps",
    "Water Reservoirs": "WaterReservoirs",
    "Water Services": "WaterServices",
    "Water Treatment Facility": "WaterTreatFacility",
    "Water Treatment Systems": "WaterTreatmentSystems",
    "Water Valves": "WaterValves",
    "Wharves": "Wharves"
}

COMPONENT_VALUES = {
    'Acquisition Fair Value': 'BulkAcquisitionFairValue',
    'Acquisition Historical': 'BulkAcquisitionHistorical',
    'Add Component': 'BulkAddComponent',
    'Adjustment Valuation': 'BulkAdjustmentValuation',
    'CapEx Valuation': 'BulkFairValueCapExValuations',
    'Create Treatment': 'BulkCreateCapExTreatments',
    'Disposal Valuation': 'BulkDisposalValuation',
    'External Valuation': 'BulkExternalValuation',
    'Impairment Valuation': 'BulkImpairmentValuation',
    'Update Component': 'BulkUpdateComponent',
    'Update Treatment': 'BulkUpdateCapExTreatments'
}

MAPPING_VALUES = {
    'Asset Spatial': 'ComplexAssetSpatialLocation',
    'Asset Address': 'ComplexAssetAddress'
}

NETWORK_MEASURE_VALUES = {
    'Add/Update Box': 'BulkAddNetworkMeasureForBoxShape',
    'Add/Update Circle': 'BulkAddNetworkMeasureForCircleShape',
    'Add/Update Horizontal Cylinder': 'BulkAddNetworkMeasureForHorizontalCylinderShape',
    'Add/Update Irregular': 'BulkAddNetworkMeasureForIrregularShape',
    'Add/Update Network Measure (without shape)': 'BulkAddNetworkMeasureWithoutShapes',
    'Add/Update Rectangle': 'BulkAddNetworkMeasureForRectangleShape',
    'Add/Update Trapezoid': 'BulkAddNetworkMeasureForTrapezoidShape',
    'Add/Update Vertical Cylinder': 'BulkAddNetworkMeasureForVerticalCylinderShape'
}

ASSETS_ASSOCIATIONS_VALUES = {
    'Asset to Asset': 'ComplexAssetToComplexAssetAssociation',
    'Functional Location to Asset': 'GroupAssetComplexAssetAssociation',
    'Functional Location to Functional Location': 'GroupAssetGroupAssetAssociation',
    'Remove Asset to Asset': 'ComplexAssetToComplexAssetAssociationUnlink'
}
