depends = ('ITKPyBase', 'ITKStatistics', 'ITKSpatialObjects', 'ITKRegistrationMethodsv4', 'ITKMetricsv4', 'ITKImageStatistics', 'ITKImageSources', 'ITKImageIntensity', 'ITKImageGradient', 'ITKImageFunction', 'ITKImageCompose', 'ITKFFT', 'ITKDisplacementField', 'ITKCommon', 'ITKCommon', )
templates = (
  ('TimeVaryingVelocityFieldSemiLagrangianTransform', 'itk::TimeVaryingVelocityFieldSemiLagrangianTransform', 'itkTimeVaryingVelocityFieldSemiLagrangianTransformD2', True, 'double,2'),
  ('TimeVaryingVelocityFieldSemiLagrangianTransform', 'itk::TimeVaryingVelocityFieldSemiLagrangianTransform', 'itkTimeVaryingVelocityFieldSemiLagrangianTransformD3', True, 'double,3'),
  ('TimeVaryingVelocityFieldSemiLagrangianTransform', 'itk::TimeVaryingVelocityFieldSemiLagrangianTransform', 'itkTimeVaryingVelocityFieldSemiLagrangianTransformD4', True, 'double,4'),
  ('DataObjectDecorator', 'itk::DataObjectDecorator', 'itkDataObjectDecoratorTVVFSLTD2', False, 'itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 2 >'),
  ('DataObjectDecorator', 'itk::DataObjectDecorator', 'itkDataObjectDecoratorTVVFSLTD3', False, 'itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 3 >'),
  ('DataObjectDecorator', 'itk::DataObjectDecorator', 'itkDataObjectDecoratorTVVFSLTD4', False, 'itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 4 >'),
  ('ImageRegistrationMethodv4', 'itk::ImageRegistrationMethodv4', 'itkImageRegistrationMethodv4IF2IF2TVVFSLTD2', False, 'itk::Image< float,2 >, itk::Image< float,2 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 2 >'),
  ('ImageRegistrationMethodv4', 'itk::ImageRegistrationMethodv4', 'itkImageRegistrationMethodv4ID2ID2TVVFSLTD2', False, 'itk::Image< double,2 >, itk::Image< double,2 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 2 >'),
  ('ImageRegistrationMethodv4', 'itk::ImageRegistrationMethodv4', 'itkImageRegistrationMethodv4IF3IF3TVVFSLTD3', False, 'itk::Image< float,3 >, itk::Image< float,3 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 3 >'),
  ('ImageRegistrationMethodv4', 'itk::ImageRegistrationMethodv4', 'itkImageRegistrationMethodv4ID3ID3TVVFSLTD3', False, 'itk::Image< double,3 >, itk::Image< double,3 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 3 >'),
  ('ImageRegistrationMethodv4', 'itk::ImageRegistrationMethodv4', 'itkImageRegistrationMethodv4IF4IF4TVVFSLTD4', False, 'itk::Image< float,4 >, itk::Image< float,4 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 4 >'),
  ('ImageRegistrationMethodv4', 'itk::ImageRegistrationMethodv4', 'itkImageRegistrationMethodv4ID4ID4TVVFSLTD4', False, 'itk::Image< double,4 >, itk::Image< double,4 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 4 >'),
  ('TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itk::TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itkTimeVaryingVelocityFieldImageRegistrationMethodv4IF2IF2TVVFSLT', False, 'itk::Image< float,2 >, itk::Image< float,2 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 2 >'),
  ('TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itk::TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itkTimeVaryingVelocityFieldImageRegistrationMethodv4ID2ID2TVVFSLT', False, 'itk::Image< double,2 >, itk::Image< double,2 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 2 >'),
  ('TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itk::TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itkTimeVaryingVelocityFieldImageRegistrationMethodv4IF3IF3TVVFSLT', False, 'itk::Image< float,3 >, itk::Image< float,3 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 3 >'),
  ('TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itk::TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itkTimeVaryingVelocityFieldImageRegistrationMethodv4ID3ID3TVVFSLT', False, 'itk::Image< double,3 >, itk::Image< double,3 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 3 >'),
  ('TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itk::TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itkTimeVaryingVelocityFieldImageRegistrationMethodv4IF4IF4TVVFSLT', False, 'itk::Image< float,4 >, itk::Image< float,4 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 4 >'),
  ('TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itk::TimeVaryingVelocityFieldImageRegistrationMethodv4', 'itkTimeVaryingVelocityFieldImageRegistrationMethodv4ID4ID4TVVFSLT', False, 'itk::Image< double,4 >, itk::Image< double,4 >, itk::TimeVaryingVelocityFieldSemiLagrangianTransform< double, 4 >'),
  ('MetamorphosisImageRegistrationMethodv4', 'itk::MetamorphosisImageRegistrationMethodv4', 'itkMetamorphosisImageRegistrationMethodv4IF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MetamorphosisImageRegistrationMethodv4', 'itk::MetamorphosisImageRegistrationMethodv4', 'itkMetamorphosisImageRegistrationMethodv4IF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MetamorphosisImageRegistrationMethodv4', 'itk::MetamorphosisImageRegistrationMethodv4', 'itkMetamorphosisImageRegistrationMethodv4IF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('MetamorphosisImageRegistrationMethodv4', 'itk::MetamorphosisImageRegistrationMethodv4', 'itkMetamorphosisImageRegistrationMethodv4ID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MetamorphosisImageRegistrationMethodv4', 'itk::MetamorphosisImageRegistrationMethodv4', 'itkMetamorphosisImageRegistrationMethodv4ID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MetamorphosisImageRegistrationMethodv4', 'itk::MetamorphosisImageRegistrationMethodv4', 'itkMetamorphosisImageRegistrationMethodv4ID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionISS2D', True, 'itk::Image< signed short,2 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIUC2D', True, 'itk::Image< unsigned char,2 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIUS2D', True, 'itk::Image< unsigned short,2 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIF2D', True, 'itk::Image< float,2 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionID2D', True, 'itk::Image< double,2 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionISS3D', True, 'itk::Image< signed short,3 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIUC3D', True, 'itk::Image< unsigned char,3 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIUS3D', True, 'itk::Image< unsigned short,3 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIF3D', True, 'itk::Image< float,3 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionID3D', True, 'itk::Image< double,3 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionISS4D', True, 'itk::Image< signed short,4 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIUC4D', True, 'itk::Image< unsigned char,4 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIUS4D', True, 'itk::Image< unsigned short,4 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionIF4D', True, 'itk::Image< float,4 >,double'),
  ('WrapExtrapolateImageFunction', 'itk::WrapExtrapolateImageFunction', 'itkWrapExtrapolateImageFunctionID4D', True, 'itk::Image< double,4 >,double'),
)
