
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-08T16:22:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "573484afff53e73e8dc3b68384ef4d323e2c60e3",
 "version": "v2021.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
