
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-09T15:19:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "016ad25dc52307027e981b69261329956681c805",
 "version": "0.8.268"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
