
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-02T09:43:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b116ee6119ff2b2acef65f0f1d0bfeb893e279c6",
 "version": "1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
